// Generated by Blueprint v0.3 from hello-world.bp
// Do not edit directly — modify the .bp source and run `bp build`
import { Hono } from 'hono';
import { serve } from '@hono/node-server';
import { secureHeaders } from 'hono/secure-headers';
import { env } from './lib/env.js';
import { healthRoutes } from './routes/health.js';
import { helloRoutes } from './routes/hello.js';

const app = new Hono();

app.use('*', secureHeaders());

app.route('/', healthRoutes);
app.route('/', helloRoutes);

app.get('/health', (c) => c.json({ status: 'ok', uptime: process.uptime() }));

app.onError((err, c) => {
  console.error(err);
  return c.json({ error: 'Internal server error' }, 500);
});

console.log('%s listening on port %d', 'hello-world', 3000);
const server = serve({ fetch: app.fetch, port: 3000 });

// Graceful shutdown
const shutdown = async () => {
  console.log('Shutting down gracefully...');
  server.close();
  process.exit(0);
};
process.on('SIGTERM', shutdown);
process.on('SIGINT', shutdown);

export default app;
