// Generated by Blueprint from todo-api.bp
// Do not edit directly — modify the .bp source and run `bp build`
import { Hono } from 'hono';
import { serve } from '@hono/node-server';
import { secureHeaders } from 'hono/secure-headers';
import { env } from './lib/env.js';
import { db } from './lib/db.js';
import { cors } from 'hono/cors';
import { todosRoutes } from './routes/todos.js';

const app = new Hono();

app.use('*', secureHeaders());
app.use('*', cors());

app.route('/', todosRoutes);

app.get('/health', (c) => c.json({ status: 'ok', uptime: process.uptime() }));

app.onError((err, c) => {
  console.error(err);
  return c.json({ error: 'Internal server error' }, 500 as const);
});

if (!process.env.VITEST) {
  console.log('%s listening on port %d', "todo-api", 3000);
  const server = serve({ fetch: app.fetch, port: 3000 });
  const shutdown = async () => {
    console.log('Shutting down gracefully...');
    await new Promise<void>((resolve) => server.close(() => resolve()));
    // Close database pool
    await db.$client.end();
    process.exit(0);
  };
  process.on('SIGTERM', shutdown);
  process.on('SIGINT', shutdown);
}

export default app;
