// Generated by Blueprint v0.2.0 from todo-api.bp
// Do not edit directly — modify the .bp source and run `bp build`
import { Hono } from 'hono';
import { zValidator } from '@hono/zod-validator';
import { z } from 'zod';
import { db } from '../lib/db.js';
import * as schema from '../models/schema.js';
import { eq, and, or, lt, gt, lte, gte, ne, sql, desc, asc, inArray } from 'drizzle-orm';
import { getTodosSchema, patchTodosSchema, postTodosSchema } from '../validation/schemas.js';
import { BpError } from '../lib/errors.js';

export const todosRoutes = new Hono();

// GET /api/todos
// List all todos with pagination
todosRoutes.get('/api/todos', zValidator('query', getTodosSchema), async (c) => {
  try {
    const page = c.req.valid('query').page;
    const perPage = c.req.valid('query').per_page;
    const todos = await (async () => { const _items = await db.select().from(schema.todo).limit(perPage).offset((page - 1) * perPage); const [{value: _ct}] = await db.select({value: sql`count(*)`}).from(schema.todo); return { items: _items, total: Number(_ct) }; })();
    return c.json({ todos: todos.items.map((r: any) => ({ id: r.id, title: r.title, done: r.done, created: r.created })), total: todos.total, page: page }, 200 as const);
  } catch (err) {
    if (err instanceof BpError) return c.json({ error: err.message }, err.statusCode);
    throw err;
  }
});

// POST /api/todos
// Create a new todo
todosRoutes.post('/api/todos', zValidator('json', postTodosSchema), async (c) => {
  try {
    const title = c.req.valid('json').title;
    const todo = (await db.insert(schema.todo).values({ title: title }).returning())[0];
    return c.json({ id: todo.id, title: todo.title, done: todo.done }, 201 as const);
  } catch (err) {
    if (err instanceof BpError) return c.json({ error: err.message }, err.statusCode);
    throw err;
  }
});

// GET /api/todos/:id
// Get a specific todo
todosRoutes.get('/api/todos/:id', async (c) => {
  try {
    const id = z.string().uuid().parse(c.req.param('id'));
    const todo = (await db.select().from(schema.todo).where(eq(schema.todo.id, id)))[0];
    if (!(todo)) return c.json({ error: "Todo not found" }, 404 as const);
    return c.json({ id: todo.id, title: todo.title, done: todo.done, created: todo.created }, 200 as const);
  } catch (err) {
    if (err instanceof BpError) return c.json({ error: err.message }, err.statusCode);
    throw err;
  }
});

// PATCH /api/todos/:id
// Toggle todo completion
todosRoutes.patch('/api/todos/:id', zValidator('json', patchTodosSchema), async (c) => {
  try {
    const id = z.string().uuid().parse(c.req.param('id'));
    const done = c.req.valid('json').done;
    let todo = (await db.select().from(schema.todo).where(eq(schema.todo.id, id)))[0];
    if (!(todo)) return c.json({ error: "Todo not found" }, 404 as const);
    todo = (await db.update(schema.todo).set(Object.fromEntries(Object.entries({ done: done }).filter(([_, v]) => v !== undefined))).where(eq(schema.todo.id, todo.id)).returning())[0];
    return c.json({ id: todo.id, done: done }, 200 as const);
  } catch (err) {
    if (err instanceof BpError) return c.json({ error: err.message }, err.statusCode);
    throw err;
  }
});

// DELETE /api/todos/:id
// Delete a todo
todosRoutes.delete('/api/todos/:id', async (c) => {
  try {
    const id = z.string().uuid().parse(c.req.param('id'));
    const todo = (await db.select().from(schema.todo).where(eq(schema.todo.id, id)))[0];
    if (!(todo)) return c.json({ error: "Todo not found" }, 404 as const);
    await db.delete(schema.todo).where(eq(schema.todo.id, todo.id));
    return c.body(null, 204 as const);
  } catch (err) {
    if (err instanceof BpError) return c.json({ error: err.message }, err.statusCode);
    throw err;
  }
});

