// Generated by Blueprint v0.2.0 from todo-api.bp
// Do not edit directly — modify the .bp source and run `bp build`
import { z } from 'zod';

export const getTodosSchema = z.object({
  page: z.coerce.number().int().min(1).default(1),
  perPage: z.coerce.number().int().min(1).max(100).default(20),
});

export const postTodosSchema = z.object({
  title: z.string(),
});

export const patchTodosSchema = z.object({
  done: z.boolean(),
});

