// Generated by Blueprint from hello-world.bp
// Do not edit directly — modify the .bp source and run `bp build`
import { z } from 'zod';

export const ApiErrorSchema = z.object({
  error: z.string(),
}).passthrough();

export const paginatedResultSchema = <T extends z.ZodTypeAny>(itemSchema: T) => z.object({
  items: z.array(itemSchema),
  total: z.number().int(),
});

export const GetHealthResponseSchema = z.object({
    status: z.string(),
    version: z.string(),
  });

export const GetHelloByNameRequestSchema = z.object({
  name: z.string(),
});

export const GetHelloByNameResponseSchema = z.object({
    message: z.string(),
  });

