package python

import (
	"github.com/abdul-hamid-achik/blueprint/internal/codegen"
)

// genDBPy emits src/lib/db.py — a synchronous SQLAlchemy engine + SessionLocal
// + `get_db` FastAPI dependency. Phase 2 uses sync sessions; Phase 3 (when
// endpoint bodies start emitting data ops) will revisit for async with
// `create_async_engine` if performance demands it.
func (g *Generator) genDBPy() codegen.OutputFile {
	content := fileHeader(g.sourceFile) + `from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker, Session
from typing import Iterator

from src.lib.env import env

engine = create_engine(env.DATABASE_URL, pool_pre_ping=True, future=True)
SessionLocal = sessionmaker(bind=engine, autoflush=False, autocommit=False, future=True)


def get_db() -> Iterator[Session]:
    """FastAPI dependency that yields a SQLAlchemy session per request."""
    db = SessionLocal()
    try:
        yield db
    except Exception:
        db.rollback()
        raise
    finally:
        db.close()
`
	return codegen.OutputFile{Path: "src/lib/db.py", Content: []byte(content)}
}

// genAlembicIni emits alembic.ini at the project root pointing at the
// generated `alembic/` script location. The DB URL is sourced from the
// DATABASE_URL env var at migrate time (alembic supports env interpolation),
// so the URL never ends up hard-coded in version-controlled config.
func (g *Generator) genAlembicIni() codegen.OutputFile {
	content := `# Generated by Blueprint — Alembic config for the Python target.
# Run migrations with: uv run alembic upgrade head
# Generate a new migration with: uv run alembic revision --autogenerate -m "..."
[alembic]
script_location = alembic
prepend_sys_path = .
version_path_separator = os

# The actual URL comes from env.py at runtime; keep it empty here so the
# config never ships a real connection string.
sqlalchemy.url =

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
`
	return codegen.OutputFile{Path: "alembic.ini", Content: []byte(content)}
}

// genAlembicEnv emits alembic/env.py — the script Alembic runs for every
// `alembic` command. It pulls Base.metadata from the generated schema so
// `--autogenerate` produces the right diffs.
func (g *Generator) genAlembicEnv() codegen.OutputFile {
	content := fileHeader(g.sourceFile) + `from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

from src.lib.env import env
from src.models.schema import Base

config = context.config
config.set_main_option("sqlalchemy.url", env.DATABASE_URL)

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


def run_migrations_offline() -> None:
    context.configure(
        url=config.get_main_option("sqlalchemy.url"),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
`
	return codegen.OutputFile{Path: "alembic/env.py", Content: []byte(content)}
}

// genAlembicScriptMako emits alembic/script.py.mako — the template Alembic
// uses when creating new migration files. We ship the standard Alembic
// default rather than try to be clever; users can edit it freely (it's
// user-owned via WriteOutputFiles).
func (g *Generator) genAlembicScriptMako() codegen.OutputFile {
	content := `"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
${imports if imports else ""}

# revision identifiers, used by Alembic.
revision: str = ${repr(up_revision)}
down_revision: Union[str, None] = ${repr(down_revision)}
branch_labels: Union[str, Sequence[str], None] = ${repr(branch_labels)}
depends_on: Union[str, Sequence[str], None] = ${repr(depends_on)}


def upgrade() -> None:
    ${upgrades if upgrades else "pass"}


def downgrade() -> None:
    ${downgrades if downgrades else "pass"}
`
	return codegen.OutputFile{
		Path:      "alembic/script.py.mako",
		Content:   []byte(content),
		UserOwned: true,
	}
}

// genAlembicVersionsInit places an __init__.py in alembic/versions so Python
// recognises the dir as a package (Alembic requires the dir to exist before
// the first `revision` command).
func (g *Generator) genAlembicVersionsInit() codegen.OutputFile {
	return codegen.OutputFile{
		Path:    "alembic/versions/__init__.py",
		Content: []byte("# Auto-generated migrations land here.\n"),
	}
}
