package python

import (
	"fmt"
	"strings"

	"github.com/abdul-hamid-achik/blueprint/internal/ast"
	"github.com/abdul-hamid-achik/blueprint/internal/codegen"
)

// fileHeader returns the standard "Generated by Blueprint" comment block
// for Python files. Mirrors the JS-side header but uses `#` comments.
// Version is intentionally omitted — see js/helpers.go fileHeader for rationale.
func fileHeader(sourceFile string) string {
	return fmt.Sprintf(
		"# Generated by Blueprint from %s\n"+
			"# Do not edit directly — modify the .bp source and run `bp build`\n",
		sourceFile)
}

// emptyInit is the Python convention `__init__.py` marker. We emit one for
// every package so editors and `uv run` resolve them as proper modules.
func emptyInit(path, source string) codegen.OutputFile {
	return codegen.OutputFile{
		Path:    path,
		Content: []byte(fileHeader(source)),
	}
}

// genPyProjectTOML emits pyproject.toml for uv. SQLAlchemy + psycopg + alembic
// are added when the spec declares a database; otherwise the lighter Phase 1
// dep set is used so projects without a DB don't pull in unused libraries.
func (g *Generator) genPyProjectTOML(bp *ast.Blueprint, hasDB, hasCache, hasStream bool) codegen.OutputFile {
	name := bp.Name
	version := blueprintEntry(bp, "version")
	if version == "" {
		version = "0.1.0"
	}

	deps := []string{
		`"fastapi>=0.115"`,
		`"uvicorn[standard]>=0.32"`,
		`"pydantic>=2.9"`,
		`"pydantic-settings>=2.6"`,
	}
	if hasDB {
		deps = append(deps,
			`"sqlalchemy>=2.0"`,
			`"psycopg[binary]>=3.2"`,
			`"alembic>=1.14"`,
		)
	}
	if hasCache {
		// Phase 5: Redis client. The async client (redis.asyncio) is the same
		// package; we expose a sync interface in src/lib/cache.py to mirror
		// the sync SQLAlchemy session shape.
		deps = append(deps, `"redis>=5.0"`)
	}
	if hasStream {
		// Phase 5: SSE helper. Plain StreamingResponse works too, but
		// sse-starlette handles client-disconnect detection and ping framing.
		deps = append(deps, `"sse-starlette>=2.1"`)
	}
	depBlock := "  " + strings.Join(deps, ",\n  ") + ","

	devDeps := []string{
		`"pytest>=8"`,
		`"httpx>=0.27"`,
	}
	if g.genTests {
		// Real-Postgres harness for the auto-generated contract suite
		// (--gen-tests). Pinned to the 4.x series so the API we depend on
		// (PostgresContainer.get_connection_url) is stable.
		devDeps = append(devDeps, `"testcontainers[postgresql]>=4.0"`)
	}
	devBlock := "  " + strings.Join(devDeps, ",\n  ") + ","

	content := fmt.Sprintf(`# Generated by Blueprint from %s
# Run with: uv sync && uv run uvicorn src.app:app --port %d
[project]
name = "%s"
version = "%s"
description = "Generated by Blueprint"
requires-python = ">=3.11"
dependencies = [
%s
]

[dependency-groups]
dev = [
%s
]
`, g.sourceFile, blueprintEntryInt(bp, "port", 3000), name, version, depBlock, devBlock)

	return codegen.OutputFile{Path: "pyproject.toml", Content: []byte(content)}
}

// genReadme tells a fresh-clone user what to do. The migrations block is
// included only when the spec declares a database — for static-endpoint
// projects there's nothing to migrate.
func (g *Generator) genReadme(bp *ast.Blueprint, hasDB bool) codegen.OutputFile {
	port := blueprintEntryInt(bp, "port", 3000)
	migrations := ""
	if hasDB {
		migrations = `
## Migrate

` + "```" + `bash
# Generate the first migration after editing models in the .bp source:
uv run alembic revision --autogenerate -m "init"
# Apply migrations to the database pointed at by DATABASE_URL:
uv run alembic upgrade head
` + "```" + `
`
	}
	content := fmt.Sprintf(`# %s

Generated by [Blueprint](https://github.com/abdul-hamid-achik/blueprint) from
`+"`%s`"+`. Do not edit by hand — modify the `+"`.bp`"+` source and re-run
`+"`bp build --target python`"+`.

## Run

`+"```"+`bash
uv sync
uv run uvicorn src.app:app --port %d --reload
`+"```"+`
%s
## Test

`+"```"+`bash
uv run pytest
`+"```"+`
`, bp.Name, g.sourceFile, port, migrations)
	return codegen.OutputFile{Path: "README.md", Content: []byte(content)}
}

// genEnvPy emits the Pydantic Settings module. Required secrets become
// required fields; optional secrets become Optional fields. When the spec
// declares a database, DATABASE_URL is added as a required field even if the
// .bp source didn't declare it as a secret (Alembic and db.py both need it).
func (g *Generator) genEnvPy(secrets []*ast.Secret, hasDB, hasCache bool) codegen.OutputFile {
	var b strings.Builder
	b.WriteString(fileHeader(g.sourceFile))
	b.WriteString("from pydantic_settings import BaseSettings, SettingsConfigDict\n")
	hasOptional := false
	for _, s := range secrets {
		if !s.Required {
			hasOptional = true
			break
		}
	}
	if hasOptional {
		b.WriteString("from typing import Optional\n")
	}
	b.WriteString("\n\nclass Settings(BaseSettings):\n")
	b.WriteString("    model_config = SettingsConfigDict(env_file=\".env\", env_file_encoding=\"utf-8\", extra=\"ignore\")\n\n")

	declared := map[string]bool{}
	for _, s := range secrets {
		declared[s.Name] = true
		if s.Required {
			fmt.Fprintf(&b, "    %s: str\n", s.Name)
		} else {
			defaultValue := "None"
			if value, ok := s.Default.(*ast.StringLit); ok {
				defaultValue = pyStringLiteral(value.Value)
			}
			fmt.Fprintf(&b, "    %s: Optional[str] = %s\n", s.Name, defaultValue)
		}
	}
	if hasDB && !declared["DATABASE_URL"] {
		b.WriteString("    DATABASE_URL: str\n")
	}
	if hasCache && !declared["REDIS_URL"] {
		// `cache redis` doesn't require the user to declare REDIS_URL as a
		// secret — we add it with a localhost default so `uv run` works out
		// of the box against a local Redis.
		b.WriteString("    REDIS_URL: str = \"redis://localhost:6379/0\"\n")
	}
	if len(secrets) == 0 && !hasDB && !hasCache {
		b.WriteString("    pass\n")
	}

	b.WriteString("\n\nenv = Settings()\n")
	return codegen.OutputFile{Path: "src/lib/env.py", Content: []byte(b.String())}
}

// genAppPy emits the FastAPI app entry. Each route module is imported and
// included via include_router. Endpoint resources are listed deterministically.
func (g *Generator) genAppPy(bp *ast.Blueprint, endpoints []*ast.Endpoint) codegen.OutputFile {
	resources := orderedResources(endpoints)
	streamResources := g.orderedStreamResources()
	wsResources := g.orderedWsResources()

	var b strings.Builder
	b.WriteString(fileHeader(g.sourceFile))
	b.WriteString("from fastapi import FastAPI\n")
	for _, r := range resources {
		fmt.Fprintf(&b, "from src.routes import %s\n", pyModuleName(r))
	}
	for _, r := range streamResources {
		fmt.Fprintf(&b, "from src.routes import %s as %s\n",
			pyModuleName(r)+"_stream", pyModuleName(r)+"_stream")
	}
	for _, r := range wsResources {
		fmt.Fprintf(&b, "from src.routes import %s as %s\n",
			pyModuleName(r)+"_ws", pyModuleName(r)+"_ws")
	}
	b.WriteString("\n")
	version := blueprintEntry(bp, "version")
	if version == "" {
		version = "0.1.0"
	}
	fmt.Fprintf(&b, "app = FastAPI(title=%q, version=%q)\n\n", bp.Name, version)
	for _, r := range resources {
		fmt.Fprintf(&b, "app.include_router(%s.router)\n", pyModuleName(r))
	}
	for _, r := range streamResources {
		fmt.Fprintf(&b, "app.include_router(%s_stream.router)\n", pyModuleName(r))
	}
	for _, r := range wsResources {
		fmt.Fprintf(&b, "app.include_router(%s_ws.router)\n", pyModuleName(r))
	}
	return codegen.OutputFile{Path: "src/app.py", Content: []byte(b.String())}
}

// orderedStreamResources returns the unique sorted list of resource names
// across the file's STREAM endpoints.
func (g *Generator) orderedStreamResources() []string {
	if g.file == nil {
		return nil
	}
	seen := map[string]bool{}
	var out []string
	for _, b := range g.file.Blocks {
		if se, ok := b.(*ast.StreamEndpoint); ok {
			r := streamResource(se.Path)
			if !seen[r] {
				seen[r] = true
				out = append(out, r)
			}
		}
	}
	for i := 1; i < len(out); i++ {
		for j := i; j > 0 && out[j-1] > out[j]; j-- {
			out[j], out[j-1] = out[j-1], out[j]
		}
	}
	return out
}

// orderedWsResources mirrors orderedStreamResources for WS endpoints.
func (g *Generator) orderedWsResources() []string {
	if g.file == nil {
		return nil
	}
	seen := map[string]bool{}
	var out []string
	for _, b := range g.file.Blocks {
		if we, ok := b.(*ast.WsEndpoint); ok {
			r := wsResource(we.Path)
			if !seen[r] {
				seen[r] = true
				out = append(out, r)
			}
		}
	}
	for i := 1; i < len(out); i++ {
		for j := i; j > 0 && out[j-1] > out[j]; j-- {
			out[j], out[j-1] = out[j-1], out[j]
		}
	}
	return out
}

// blueprintEntryInt returns an integer entry from the blueprint block, or
// `fallback` if absent or the value isn't an int literal.
func blueprintEntryInt(bp *ast.Blueprint, key string, fallback int) int {
	if bp == nil {
		return fallback
	}
	for _, e := range bp.Entries {
		if e.Key != key {
			continue
		}
		if il, ok := e.Value.(*ast.IntLit); ok {
			var n int
			if _, err := fmt.Sscanf(il.Value, "%d", &n); err == nil {
				return n
			}
		}
	}
	return fallback
}
