// Generated by Blueprint v0.2.0 from todo-api.bp
// Do not edit directly — modify the .bp source and run `bp build`
// Frontend-safe types generated from your Blueprint schema and endpoints

export type PaginatedResult<T> = {
  items: T[];
  total: number;
};

export interface ApiError {
  status: number;
  message: string;
  body?: unknown;
}

export interface Todo {
  id: string;
  title: string;
  done: boolean;
  created: Date;
}

export interface GetTodosRequest {
  page?: number;
  per_page?: number;
}

export type GetTodosResponse = {
    todos: Todo[];
    total: number;
    page: number;
  };

export interface PostTodosRequest {
  title: string;
}

export type PostTodosResponse = {
    id: string;
    title: string;
    done: boolean;
  };

export interface GetTodosByIdRequest {
  id: string;
}

export type GetTodosByIdResponse = {
    id: string;
    title: string;
    done: boolean;
    created: Date;
  };

export interface PatchTodosByIdRequest {
  id: string;
  done: boolean;
}

export type PatchTodosByIdResponse = {
    id: string;
    done: boolean;
  };

export interface DeleteTodosByIdRequest {
  id: string;
}

export type DeleteTodosByIdResponse = void;

export interface WsConnection<TMessage = unknown> {
  socket: unknown;
  send(data: unknown): void;
  close(code?: number, reason?: string): void;
  onOpen(handler: () => void): void;
  onMessage(handler: (message: TMessage) => void): void;
  onClose(handler: (event: unknown) => void): void;
  onError(handler: (event: unknown) => void): void;
}

export interface RestApiClient {
  getTodos(input: GetTodosRequest): Promise<GetTodosResponse>;
  postTodos(input: PostTodosRequest): Promise<PostTodosResponse>;
  getTodosById(input: GetTodosByIdRequest): Promise<GetTodosByIdResponse>;
  patchTodosById(input: PatchTodosByIdRequest): Promise<PatchTodosByIdResponse>;
  deleteTodosById(input: DeleteTodosByIdRequest): Promise<DeleteTodosByIdResponse>;
}

export interface StreamApiClient {
}

export interface WsApiClient {
}

export interface ApiClient {
  rest: RestApiClient;
  streams: StreamApiClient;
  ws: WsApiClient;
}
