// Generated by Blueprint v0.2.0 from todo-api.bp
// Do not edit directly — modify the .bp source and run `bp build`
import type * as Api from './api.js';
import * as Schemas from './schemas.js';

type SchemaParser = { parse(value: unknown): unknown };

interface EventSourceLike {
  addEventListener(type: string, listener: (event: { data: string }) => void): void;
  close(): void;
  onerror: ((event: unknown) => void) | null;
  onopen?: ((event: unknown) => void) | null;
}

interface WebSocketLike {
  addEventListener(type: string, listener: (event: any) => void): void;
  send(data: string): void;
  close(code?: number, reason?: string): void;
}

export interface ApiClientOptions {
  baseUrl: string;
  validateResponses?: boolean;
  getAuthHeader?: () => string | null | undefined;
  fetch?: typeof fetch;
  createEventSource?: (url: string) => EventSourceLike;
  createWebSocket?: (url: string) => WebSocketLike;
}

export class ApiClientError extends Error implements Api.ApiError {
  status: number;
  body?: unknown;

  constructor(status: number, message: string, body?: unknown) {
    super(message);
    this.name = 'ApiClientError';
    this.status = status;
    this.body = body;
  }
}

function trimTrailingSlashes(value: string): string {
  return value.replace(/\/+$/, '');
}

function serializeValue(value: unknown): string {
  if (value instanceof Date) return value.toISOString();
  return String(value);
}

function appendQuery(query: URLSearchParams, key: string, value: unknown): void {
  if (value === undefined || value === null) return;
  if (Array.isArray(value)) {
    for (const item of value) {
      query.append(key, serializeValue(item));
    }
    return;
  }
  query.set(key, serializeValue(value));
}

function safeJsonParse(value: string): unknown {
  try {
    return JSON.parse(value);
  } catch {
    return value;
  }
}

async function readResponseBody(res: Response): Promise<unknown> {
  const text = await res.text();
  if (!text) return undefined;
  const contentType = res.headers.get('content-type') ?? '';
  if (contentType.includes('application/json')) {
    return safeJsonParse(text);
  }
  return text;
}

function buildHeaders(getAuthHeader?: () => string | null | undefined): HeadersInit {
  const headers: Record<string, string> = {};
  const authHeader = getAuthHeader?.();
  if (authHeader) headers.Authorization = authHeader;
  return headers;
}

function toWebSocketUrl(baseUrl: string, path: string): string {
  const url = new URL(path, `${trimTrailingSlashes(baseUrl)}/`);
  url.protocol = url.protocol === 'https:' ? 'wss:' : 'ws:';
  return url.toString();
}

async function requestJson<T>(
  doFetch: typeof fetch,
  url: string,
  init: RequestInit,
  schema: SchemaParser | null,
  validateResponses: boolean,
): Promise<T> {
  const res = await doFetch(url, init);
  const body = await readResponseBody(res);
  if (!res.ok) {
    const parsedError = body === undefined ? undefined : Schemas.ApiErrorSchema.safeParse(body);
    const message = parsedError?.success ? parsedError.data.error : `Request failed with status ${res.status}`;
    throw new ApiClientError(res.status, message, body);
  }
  if (!schema || body === undefined) {
    return body as T;
  }
  return (validateResponses ? schema.parse(body) : body) as T;
}

function parseEventPayload<T>(schema: SchemaParser, raw: string, validateResponses: boolean): T {
  const parsed = safeJsonParse(raw);
  return (validateResponses ? schema.parse(parsed) : parsed) as T;
}

export function createApiClient(options: ApiClientOptions): Api.ApiClient {
  const baseUrl = trimTrailingSlashes(options.baseUrl);
  const validateResponses = options.validateResponses ?? true;
  const doFetch = options.fetch ?? fetch;
  const createEventSource = options.createEventSource ?? ((url: string) => new (globalThis as any).EventSource(url));
  const createWebSocket = options.createWebSocket ?? ((url: string) => new (globalThis as any).WebSocket(url));

  return {
    rest: {
      async getTodos(input: Api.GetTodosRequest): Promise<Api.GetTodosResponse> {
        const request = Schemas.GetTodosRequestSchema.parse(input);
        const url = new URL('/api/todos', `${baseUrl}/`);
        appendQuery(url.searchParams, 'page', request.page);
        appendQuery(url.searchParams, 'per_page', request.per_page);
        const headers = buildHeaders(options.getAuthHeader);
        return requestJson(
          doFetch,
          url.toString(),
          { method: 'GET', headers },
          Schemas.GetTodosResponseSchema,
          validateResponses,
        ) as Promise<Api.GetTodosResponse>;
      },
      async postTodos(input: Api.PostTodosRequest): Promise<Api.PostTodosResponse> {
        const request = Schemas.PostTodosRequestSchema.parse(input);
        const url = new URL('/api/todos', `${baseUrl}/`);
        const headers = buildHeaders(options.getAuthHeader);
        const body = {title: request.title};
        return requestJson(
          doFetch,
          url.toString(),
          { method: 'POST', headers: { ...headers, 'Content-Type': 'application/json' }, body: JSON.stringify(body) },
          Schemas.PostTodosResponseSchema,
          validateResponses,
        ) as Promise<Api.PostTodosResponse>;
      },
      async getTodosById(input: Api.GetTodosByIdRequest): Promise<Api.GetTodosByIdResponse> {
        const request = Schemas.GetTodosByIdRequestSchema.parse(input);
        const url = new URL('/api/todos/:id', `${baseUrl}/`);
        url.pathname = url.pathname.replace(':id', encodeURIComponent(serializeValue(request.id)));
        const headers = buildHeaders(options.getAuthHeader);
        return requestJson(
          doFetch,
          url.toString(),
          { method: 'GET', headers },
          Schemas.GetTodosByIdResponseSchema,
          validateResponses,
        ) as Promise<Api.GetTodosByIdResponse>;
      },
      async patchTodosById(input: Api.PatchTodosByIdRequest): Promise<Api.PatchTodosByIdResponse> {
        const request = Schemas.PatchTodosByIdRequestSchema.parse(input);
        const url = new URL('/api/todos/:id', `${baseUrl}/`);
        url.pathname = url.pathname.replace(':id', encodeURIComponent(serializeValue(request.id)));
        const headers = buildHeaders(options.getAuthHeader);
        const body = {done: request.done};
        return requestJson(
          doFetch,
          url.toString(),
          { method: 'PATCH', headers: { ...headers, 'Content-Type': 'application/json' }, body: JSON.stringify(body) },
          Schemas.PatchTodosByIdResponseSchema,
          validateResponses,
        ) as Promise<Api.PatchTodosByIdResponse>;
      },
      async deleteTodosById(input: Api.DeleteTodosByIdRequest): Promise<Api.DeleteTodosByIdResponse> {
        const request = Schemas.DeleteTodosByIdRequestSchema.parse(input);
        const url = new URL('/api/todos/:id', `${baseUrl}/`);
        url.pathname = url.pathname.replace(':id', encodeURIComponent(serializeValue(request.id)));
        const headers = buildHeaders(options.getAuthHeader);
        return requestJson(
          doFetch,
          url.toString(),
          { method: 'DELETE', headers },
          null,
          validateResponses,
        ) as Promise<Api.DeleteTodosByIdResponse>;
      },
    },
    streams: {
    },
    ws: {
    },
  };
}
