// Generated by Blueprint v0.2.0 from todo-api.bp
// Do not edit directly — modify the .bp source and run `bp build`
import { z } from 'zod';

export const ApiErrorSchema = z.object({
  error: z.string(),
}).passthrough();

export const paginatedResultSchema = <T extends z.ZodTypeAny>(itemSchema: T) => z.object({
  items: z.array(itemSchema),
  total: z.number().int(),
});

export const TodoSchema = z.object({
  id: z.string().uuid(),
  title: z.string(),
  done: z.boolean(),
  created: z.coerce.date(),
});

export const GetTodosRequestSchema = z.object({
  page: z.number().int().min(1).default(1),
  per_page: z.number().int().min(1).max(100).default(20),
});

export const GetTodosResponseSchema = z.object({
    todos: z.array(z.lazy(() => TodoSchema)),
    total: z.number().int(),
    page: z.number().int(),
  });

export const PostTodosRequestSchema = z.object({
  title: z.string(),
});

export const PostTodosResponseSchema = z.object({
    id: z.string().uuid(),
    title: z.string(),
    done: z.boolean(),
  });

export const GetTodosByIdRequestSchema = z.object({
  id: z.string().uuid(),
});

export const GetTodosByIdResponseSchema = z.object({
    id: z.string().uuid(),
    title: z.string(),
    done: z.boolean(),
    created: z.coerce.date(),
  });

export const PatchTodosByIdRequestSchema = z.object({
  id: z.string().uuid(),
  done: z.boolean(),
});

export const PatchTodosByIdResponseSchema = z.object({
    id: z.string().uuid(),
    done: z.boolean(),
  });

export const DeleteTodosByIdRequestSchema = z.object({
  id: z.string().uuid(),
});

