// Generated by Blueprint v0.2.0 from hello-world.bp
// Do not edit directly — modify the .bp source and run `bp build`
// Frontend-safe types generated from your Blueprint schema and endpoints

export type PaginatedResult<T> = {
  items: T[];
  total: number;
};

export interface ApiError {
  status: number;
  message: string;
  body?: unknown;
}

export type GetHealthResponse = {
    status: string;
    version: string;
  };

export interface GetHelloByNameRequest {
  name: string;
}

export type GetHelloByNameResponse = {
    message: string;
  };

export interface WsConnection<TMessage = unknown> {
  socket: unknown;
  send(data: unknown): void;
  close(code?: number, reason?: string): void;
  onOpen(handler: () => void): void;
  onMessage(handler: (message: TMessage) => void): void;
  onClose(handler: (event: unknown) => void): void;
  onError(handler: (event: unknown) => void): void;
}

export interface RestApiClient {
  getHealth(): Promise<GetHealthResponse>;
  getHelloByName(input: GetHelloByNameRequest): Promise<GetHelloByNameResponse>;
}

export interface StreamApiClient {
}

export interface WsApiClient {
}

export interface ApiClient {
  rest: RestApiClient;
  streams: StreamApiClient;
  ws: WsApiClient;
}
