// Generated by Blueprint v0.2.0 from todo-api.bp
// Do not edit directly — modify the .bp source and run `bp build`
import { pgTable, pgEnum, text, integer, real, boolean, uuid, timestamp, jsonb } from 'drizzle-orm/pg-core';

export const todo = pgTable('todos', {
  id: uuid('id').defaultRandom().primaryKey(),
  title: text('title').notNull(),
  done: boolean('done').default(false),
  created: timestamp('created').defaultNow(),
});

export type Todo = typeof todo.$inferSelect;
export type NewTodo = typeof todo.$inferInsert;

