package js

import (
	"fmt"
	"strconv"
	"strings"
	"unicode"

	"github.com/abdul-hamid-achik/blueprint/internal/ast"
)

// toCamelCase converts snake_case to camelCase.
func toCamelCase(s string) string {
	// Split on both underscores and hyphens so that file keys like "rooms-stream"
	// produce valid JS identifiers like "roomsStream".
	s = strings.ReplaceAll(s, "-", "_")
	parts := strings.Split(s, "_")
	for i := 1; i < len(parts); i++ {
		if len(parts[i]) > 0 {
			parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
		}
	}
	return strings.Join(parts, "")
}

// toPascalCase converts snake_case or kebab-case to PascalCase.
func toPascalCase(s string) string {
	// Split on both underscores and hyphens so that names like "user-profile"
	// produce "UserProfile".
	s = strings.ReplaceAll(s, "-", "_")
	parts := strings.Split(s, "_")
	for i := range parts {
		if len(parts[i]) > 0 {
			parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
		}
	}
	return strings.Join(parts, "")
}

// toKebabCase converts snake_case to kebab-case.
func toKebabCase(s string) string {
	return strings.ReplaceAll(s, "_", "-")
}

// pluralize naively pluralizes a model name for table names.
func pluralize(s string) string {
	// Irregular forms
	irregulars := map[string]string{
		"person": "people",
		"man":    "men",
		"woman":  "women",
		"child":  "children",
		"tooth":  "teeth",
		"foot":   "feet",
		"mouse":  "mice",
		"goose":  "geese",
	}
	lower := strings.ToLower(s)
	if plural, ok := irregulars[lower]; ok {
		// Preserve case of first letter
		if len(s) > 0 && s[0] >= 'A' && s[0] <= 'Z' {
			return strings.ToUpper(plural[:1]) + plural[1:]
		}
		return plural
	}

	// All-caps acronyms (e.g., "API" -> "APIs", not "APIes")
	if strings.ToUpper(s) == s && len(s) > 1 {
		return s + "s"
	}

	if strings.HasSuffix(s, "s") || strings.HasSuffix(s, "x") || strings.HasSuffix(s, "z") ||
		strings.HasSuffix(s, "sh") || strings.HasSuffix(s, "ch") {
		return s + "es"
	}
	if strings.HasSuffix(s, "y") && len(s) > 1 {
		prev := s[len(s)-2]
		if prev != 'a' && prev != 'e' && prev != 'i' && prev != 'o' && prev != 'u' {
			return s[:len(s)-1] + "ies"
		}
	}
	return s + "s"
}

// fileHeader returns the standard generated file header comment.
func fileHeader(sourceFile string) string {
	return fmt.Sprintf("// Generated by Blueprint v0.3 from %s\n// Do not edit directly — modify the .bp source and run `bp build`\n", sourceFile)
}

// blueprintEntry extracts a string value from blueprint entries by key.
func blueprintEntry(bp *ast.Blueprint, key string) string {
	for _, e := range bp.Entries {
		if e.Key == key {
			return exprToString(e.Value)
		}
	}
	return ""
}

// blueprintEntryInt extracts an int value from blueprint entries by key.
func blueprintEntryInt(bp *ast.Blueprint, key string) int {
	for _, e := range bp.Entries {
		if e.Key == key {
			if lit, ok := e.Value.(*ast.IntLit); ok {
				n := 0
				fmt.Sscanf(lit.Value, "%d", &n)
				return n
			}
		}
	}
	return 0
}

// exprToString converts an expression to its string representation.
func exprToString(e ast.Expr) string {
	if e == nil {
		return ""
	}
	switch v := e.(type) {
	case *ast.StringLit:
		return v.Value
	case *ast.IntLit:
		return v.Value
	case *ast.FloatLit:
		return v.Value
	case *ast.BoolLit:
		if v.Value {
			return "true"
		}
		return "false"
	case *ast.NullLit:
		return "null"
	case *ast.NowLit:
		return "new Date()"
	case *ast.Ident:
		return v.Name
	case *ast.DurationLit:
		return v.Value
	case *ast.SizeLit:
		return v.Value
	case *ast.RateLit:
		return v.Value
	case *ast.ListExpr:
		elems := make([]string, len(v.Elements))
		for i, el := range v.Elements {
			elems[i] = exprToString(el)
		}
		return "[" + strings.Join(elems, ", ") + "]"
	default:
		return fmt.Sprintf("%v", e)
	}
}

// exprToJS converts an AST expression into JavaScript source code.
func exprToJS(e ast.Expr) string {
	return exprToJSWithCtx(e, nil)
}

// exprToJSWithCtx converts an AST expression into JavaScript source code,
// with optional context for resolving middleware-injected variables.
func exprToJSWithCtx(e ast.Expr, ctx *emitCtx) string {
	if e == nil {
		return "undefined"
	}
	switch v := e.(type) {
	case *ast.StringLit:
		// Handle string interpolation: replace {expr} with ${expr}
		s := v.Value
		if strings.Contains(s, "{") {
			s = strings.ReplaceAll(s, "`", "\\`")
			result := strings.Builder{}
			i := 0
			for i < len(s) {
				if s[i] == '{' {
					i++ // skip opening {
					depth := 1
					var body strings.Builder
					for i < len(s) && depth > 0 {
						if s[i] == '{' {
							depth++
						} else if s[i] == '}' {
							depth--
							if depth == 0 {
								i++ // skip closing }
								break
							}
						}
						body.WriteByte(s[i])
						i++
					}
					// Transform the interpolation body (e.g., .count -> .length)
					bodyStr := transformInterpolation(body.String())
					result.WriteString("${")
					result.WriteString(bodyStr)
					result.WriteByte('}')
				} else {
					result.WriteByte(s[i])
					i++
				}
			}
			return "`" + result.String() + "`"
		}
		return fmt.Sprintf(`"%s"`, jsEscapeString(s))
	case *ast.IntLit:
		return v.Value
	case *ast.FloatLit:
		return v.Value
	case *ast.BoolLit:
		if v.Value {
			return "true"
		}
		return "false"
	case *ast.NullLit:
		return "null"
	case *ast.NowLit:
		return "new Date()"
	case *ast.Ident:
		name := toCamelCase(v.Name)
		// If this identifier is a middleware-injected context variable, use c.get()
		// Cast (c as any) to bypass Hono's strict typed-context restriction.
		if ctx != nil && ctx.ctxVars != nil && ctx.ctxVars[v.Name] {
			return fmt.Sprintf("(c as any).get('%s')", name)
		}
		return name
	case *ast.DurationLit:
		return durationToMS(v.Value)
	case *ast.SizeLit:
		return sizeToBytes(v.Value)
	case *ast.RateLit:
		return fmt.Sprintf(`"%s"`, v.Value)
	case *ast.BinaryExpr:
		op := v.Op
		switch op {
		case "and":
			op = "&&"
		case "or":
			op = "||"
		case "in":
			return fmt.Sprintf("%s.includes(%s)", exprToJSWithCtx(v.Right, ctx), exprToJSWithCtx(v.Left, ctx))
		}
		// Date arithmetic: now + duration or now - duration
		if op == "+" || op == "-" {
			if _, ok := v.Left.(*ast.NowLit); ok {
				return fmt.Sprintf("new Date(Date.now() %s %s)", op, exprToJSWithCtx(v.Right, ctx))
			}
		}
		return fmt.Sprintf("(%s %s %s)", exprToJSWithCtx(v.Left, ctx), op, exprToJSWithCtx(v.Right, ctx))
	case *ast.UnaryExpr:
		op := v.Op
		if op == "not" {
			op = "!"
		}
		return fmt.Sprintf("%s%s", op, exprToJSWithCtx(v.Operand, ctx))
	case *ast.FnCall:
		// Handle data operations (query, save, fetch, update, delete, etc.)
		if isDataOp(v.Name) {
			return dataOpToJSWithCtx(v, ctx)
		}
		// Handle call <service> METHOD /path [body] -> await call<Service>(method, path, body?)
		if v.Name == "call" && len(v.Args) >= 1 {
			serviceName := ""
			if svc, ok := v.Args[0].(*ast.Ident); ok {
				serviceName = toPascalCase(normalizeServiceName(svc.Name))
			}
			method := "GET"
			if len(v.Args) >= 2 {
				if m, ok := v.Args[1].(*ast.Ident); ok {
					method = strings.ToUpper(m.Name)
				}
			}
			path := "/"
			if len(v.Args) >= 3 {
				if p, ok := v.Args[2].(*ast.PathExpr); ok {
					path = p.Value
				} else {
					path = exprToJSWithCtx(v.Args[2], ctx)
				}
			}
			if len(v.Args) >= 4 {
				body := exprToJSWithCtx(v.Args[3], ctx)
				return fmt.Sprintf("await call%s(%q, %q, %s)", serviceName, method, path, body)
			}
			return fmt.Sprintf("await call%s(%q, %q)", serviceName, method, path)
		}
		// Handle built-in functions
		switch v.Name {
		case "log":
			if len(v.Args) >= 2 {
				if ident, ok := v.Args[1].(*ast.Ident); ok {
					return fmt.Sprintf("console.%s(%s)", ident.Name, exprToJSWithCtx(v.Args[0], ctx))
				}
			}
			if len(v.Args) >= 1 {
				return fmt.Sprintf("console.log(%s)", exprToJSWithCtx(v.Args[0], ctx))
			}
			return "console.log()"
		case "clock":
			return "performance.now()"
		case "sleep":
			if len(v.Args) >= 1 {
				return fmt.Sprintf("await new Promise(r => setTimeout(r, %s))", exprToJSWithCtx(v.Args[0], ctx))
			}
			return "await new Promise(r => setTimeout(r, 0))"
		case "inject":
			// inject val as name -> c.set('name', val)
			if len(v.Args) >= 2 {
				name := exprToString(v.Args[1])
				val := exprToJSWithCtx(v.Args[0], ctx)
				return fmt.Sprintf("c.set('%s', %s)", name, val)
			}
			if len(v.Args) >= 1 {
				return fmt.Sprintf("c.set('value', %s)", exprToJSWithCtx(v.Args[0], ctx))
			}
			return "/* inject: missing args */"
		case "map":
			// map collection: body
			// Determine the loop variable name from the model type of the collection.
			// e.g. `map old: ...` where old is a job[] → loop var is "job"
			if len(v.Args) >= 2 {
				collectionJS := exprToJSWithCtx(v.Args[0], ctx)
				loopVar := "item"
				if ctx != nil && ctx.varModels != nil {
					if ident, ok := v.Args[0].(*ast.Ident); ok {
						varName := toCamelCase(ident.Name)
						if modelName, found := ctx.varModels[varName]; found {
							loopVar = toCamelCase(modelName)
						}
					}
				}
				// Build inner ctx with the loop variable overriding the bound var
				// so update/delete inside the map use loopVar.id instead of collection.id
				var innerCtx *emitCtx
				if ctx != nil {
					ctxCopy := *ctx
					ctxCopy.boundVars = make(map[string]string)
					for k, val := range ctx.boundVars {
						ctxCopy.boundVars[k] = val
					}
					// Override: model → loopVar instead of model → collection
					if ident, ok := v.Args[0].(*ast.Ident); ok {
						varName := toCamelCase(ident.Name)
						if modelName, found := ctx.varModels[varName]; found {
							ctxCopy.boundVars[modelName] = loopVar
						}
					}
					innerCtx = &ctxCopy
				}
				bodyJS := exprToJSWithCtx(v.Args[1], innerCtx)
				return fmt.Sprintf("await Promise.all(%s.map(async (%s) => %s))", collectionJS, loopVar, bodyJS)
			}
			if len(v.Args) >= 1 {
				return fmt.Sprintf("%s.map(item => item)", exprToJSWithCtx(v.Args[0], ctx))
			}
			return "[]"
		}
		// Generic function call — await declared async functions (fns, pipes, storage built-ins)
		args := make([]string, len(v.Args))
		for i, a := range v.Args {
			args[i] = exprToJSWithCtx(a, ctx)
		}
		callStr := fmt.Sprintf("%s(%s)", toCamelCase(v.Name), strings.Join(args, ", "))
		if ctx != nil && ctx.asyncFns != nil && ctx.asyncFns[toCamelCase(v.Name)] {
			return "await " + callStr
		}
		return callStr
	case *ast.FieldAccess:
		// N.days.ago -> new Date(Date.now() - N * 86400000)
		if v.Field == "ago" {
			if inner, ok := v.Base.(*ast.FieldAccess); ok && isDurationField(inner.Field) {
				if numLit, ok := inner.Base.(*ast.IntLit); ok {
					return fmt.Sprintf("new Date(Date.now() - %s)", durationFieldToMS(numLit.Value, inner.Field))
				}
			}
		}
		// N.days, N.hours, etc. -> milliseconds
		if isDurationField(v.Field) {
			if numLit, ok := v.Base.(*ast.IntLit); ok {
				return durationFieldToMS(numLit.Value, v.Field)
			}
		}
		// header.X-API-Key -> c.req.header('X-API-Key') as string
		// (header() returns string | undefined; cast since guards check existence before use)
		if ident, ok := v.Base.(*ast.Ident); ok && ident.Name == "header" {
			return fmt.Sprintf("(c.req.header('%s') as string)", v.Field)
		}
		// env.X_Y -> env.X_Y (keep SCREAMING_SNAKE_CASE for env var access)
		if ident, ok := v.Base.(*ast.Ident); ok && ident.Name == "env" {
			return fmt.Sprintf("env.%s", v.Field)
		}
		// .count on a collection → .length in JavaScript
		if v.Field == "count" {
			return fmt.Sprintf("%s.length", exprToJSWithCtx(v.Base, ctx))
		}
		return fmt.Sprintf("%s.%s", exprToJSWithCtx(v.Base, ctx), toCamelCase(v.Field))
	case *ast.IndexAccess:
		idx := exprToJSWithCtx(v.Index, ctx)
		// For struct enum bracket access (e.g., Plan[key.plan]), use <Name>Config[key]
		if ident, ok := v.Base.(*ast.Ident); ok {
			if ctx != nil && ctx.structEnums != nil && ctx.structEnums[ident.Name] {
				return fmt.Sprintf("%sConfig[%s as any]", ident.Name, idx)
			}
			// Cast base as any to bypass TypeScript strict index type checking
			base := exprToJSWithCtx(v.Base, ctx)
			return fmt.Sprintf("(%s as any)[%s]", base, idx)
		}
		return fmt.Sprintf("%s[%s]", exprToJSWithCtx(v.Base, ctx), idx)
	case *ast.ParenExpr:
		return fmt.Sprintf("(%s)", exprToJSWithCtx(v.Expr, ctx))
	case *ast.ListExpr:
		elems := make([]string, len(v.Elements))
		for i, el := range v.Elements {
			elems[i] = exprToJSWithCtx(el, ctx)
		}
		return fmt.Sprintf("[%s]", strings.Join(elems, ", "))
	case *ast.BlockExpr:
		pairs := make([]string, len(v.Entries))
		for i, kv := range v.Entries {
			pairs[i] = fmt.Sprintf("%s: %s", toCamelCase(kv.Key), exprToJSWithCtx(kv.Value, ctx))
		}
		return fmt.Sprintf("{ %s }", strings.Join(pairs, ", "))
	case *ast.PathExpr:
		return fmt.Sprintf(`"%s"`, v.Value)
	default:
		return "/* unknown expr */"
	}
}

// jsEscapeString escapes special characters for use inside a JavaScript double-quoted string.
func jsEscapeString(s string) string {
	var b strings.Builder
	b.Grow(len(s))
	for _, r := range s {
		switch r {
		case '\\':
			b.WriteString(`\\`)
		case '"':
			b.WriteString(`\"`)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		case '\t':
			b.WriteString(`\t`)
		default:
			b.WriteRune(r)
		}
	}
	return b.String()
}

// typeToZod converts a Blueprint type expression to a Zod schema call.
func typeToZod(t ast.TypeExpr) string {
	switch v := t.(type) {
	case *ast.PrimitiveType:
		switch v.Name {
		case "string":
			return "z.string()"
		case "int":
			return "z.number().int()"
		case "float":
			return "z.number()"
		case "bool":
			return "z.boolean()"
		case "uuid":
			return "z.string().uuid()"
		case "timestamp":
			return "z.coerce.date()"
		case "json":
			return "z.any()"
		case "file":
			return "z.any()"
		case "money":
			return "z.number()"
		default:
			return "z.any()"
		}
	case *ast.NamedType:
		return toCamelCase(v.Name) + "Schema"
	case *ast.ListType:
		return fmt.Sprintf("z.array(%s)", typeToZod(v.Element))
	case *ast.MapType:
		return fmt.Sprintf("z.record(%s, %s)", typeToZod(v.Key), typeToZod(v.Value))
	case *ast.EnumInline:
		variants := make([]string, len(v.Variants))
		for i, v := range v.Variants {
			variants[i] = fmt.Sprintf(`"%s"`, v)
		}
		return fmt.Sprintf("z.enum([%s])", strings.Join(variants, ", "))
	case *ast.MimeTypeExpr:
		return "z.any() /* MIME: " + v.Type + "/" + v.Subtype + " */"
	default:
		return "z.any()"
	}
}

// typeToZodCoerce converts a Blueprint type to a Zod schema with coercion (for query params).
func typeToZodCoerce(t ast.TypeExpr) string {
	switch v := t.(type) {
	case *ast.PrimitiveType:
		switch v.Name {
		case "int":
			return "z.coerce.number().int()"
		case "float":
			return "z.coerce.number()"
		case "bool":
			return "z.coerce.boolean()"
		}
	}
	return typeToZod(t)
}

// typeToTS converts a Blueprint type expression to a TypeScript type string.
func typeToTS(t ast.TypeExpr) string {
	switch v := t.(type) {
	case *ast.PrimitiveType:
		switch v.Name {
		case "string", "uuid":
			return "string"
		case "int", "float", "money":
			return "number"
		case "bool":
			return "boolean"
		case "timestamp":
			return "Date"
		case "json":
			return "unknown"
		case "file":
			return "File"
		default:
			return "unknown"
		}
	case *ast.NamedType:
		return toPascalCase(v.Name)
	case *ast.ListType:
		return typeToTS(v.Element) + "[]"
	case *ast.MapType:
		return fmt.Sprintf("Record<%s, %s>", typeToTS(v.Key), typeToTS(v.Value))
	case *ast.EnumInline:
		variants := make([]string, len(v.Variants))
		for i, v := range v.Variants {
			variants[i] = fmt.Sprintf(`"%s"`, v)
		}
		return strings.Join(variants, " | ")
	case *ast.MimeTypeExpr:
		return "File"
	default:
		return "unknown"
	}
}

// typeToDrizzle converts a Blueprint type expression to a Drizzle column builder.
func typeToDrizzle(t ast.TypeExpr) string {
	switch v := t.(type) {
	case *ast.PrimitiveType:
		switch v.Name {
		case "string":
			return "text"
		case "int":
			return "integer"
		case "float":
			return "real"
		case "bool":
			return "boolean"
		case "uuid":
			return "uuid"
		case "timestamp":
			return "timestamp"
		case "json":
			return "jsonb"
		case "money":
			return "integer" // store cents
		default:
			return "text"
		}
	case *ast.NamedType:
		return "text" // custom types stored as text by default
	case *ast.EnumInline:
		return "text" // inline enums stored as text
	default:
		return "text"
	}
}

// constraintsToZod appends Zod constraint methods for field constraints.
// Emits in correct order: validation (.min/.max/.email/.url) -> .optional() -> .default().
func constraintsToZod(constraints []*ast.Constraint_) string {
	var validation, optional, defaults []string
	for _, c := range constraints {
		switch c.Kind {
		case "required":
			// default in zod
		case "optional":
			optional = append(optional, ".optional()")
		case "min":
			validation = append(validation, fmt.Sprintf(".min(%s)", exprToJS(c.Value)))
		case "max":
			validation = append(validation, fmt.Sprintf(".max(%s)", exprToJS(c.Value)))
		case "format":
			if s := exprToString(c.Value); s == "email" {
				validation = append(validation, ".email()")
			} else if s == "url" {
				validation = append(validation, ".url()")
			}
		case "default":
			val := exprToJS(c.Value)
			// Ident values (e.g., enum variant names like "center") must be quoted as strings
			if _, ok := c.Value.(*ast.Ident); ok {
				val = fmt.Sprintf(`"%s"`, exprToString(c.Value))
			}
			defaults = append(defaults, fmt.Sprintf(".default(%s)", val))
		}
	}
	var parts []string
	parts = append(parts, validation...)
	parts = append(parts, optional...)
	parts = append(parts, defaults...)
	return strings.Join(parts, "")
}

// durationToMS converts a duration string like "5s" to milliseconds.
func durationToMS(s string) string {
	s = strings.TrimSpace(s)
	if strings.HasSuffix(s, "ms") {
		return strings.TrimSuffix(s, "ms")
	}
	if strings.HasSuffix(s, "s") {
		num := strings.TrimSuffix(s, "s")
		return num + " * 1000"
	}
	if strings.HasSuffix(s, "min") {
		num := strings.TrimSuffix(s, "min")
		return num + " * 60 * 1000"
	}
	if strings.HasSuffix(s, "h") {
		num := strings.TrimSuffix(s, "h")
		return num + " * 60 * 60 * 1000"
	}
	// Check if the value is purely numeric (no unit) — pass through as-is
	if _, err := strconv.Atoi(s); err == nil {
		return s
	}
	return fmt.Sprintf("/* INVALID DURATION: %s */ 0", s)
}

// sizeToBytes converts a size string like "10mb" to bytes.
func sizeToBytes(s string) string {
	s = strings.TrimSpace(s)
	lower := strings.ToLower(s)
	if strings.HasSuffix(lower, "mb") {
		num := s[:len(s)-2]
		return num + " * 1024 * 1024"
	}
	if strings.HasSuffix(lower, "kb") {
		num := s[:len(s)-2]
		return num + " * 1024"
	}
	if strings.HasSuffix(lower, "gb") {
		num := s[:len(s)-2]
		return num + " * 1024 * 1024 * 1024"
	}
	// Check if the value is purely numeric (no unit) — pass through as-is
	if _, err := strconv.Atoi(s); err == nil {
		return s
	}
	return fmt.Sprintf("/* INVALID SIZE: %s */ 0", s)
}

// pathParamTypeName extracts the type name string from a TypeExpr for path parameter validation.
// Returns "uuid", "int", "string", etc., or empty string if type is nil.
func pathParamTypeName(t ast.TypeExpr) string {
	if t == nil {
		return ""
	}
	if nt, ok := t.(*ast.NamedType); ok {
		return nt.Name
	}
	return ""
}

// parseRateLimit parses a rate string like "60/min" and returns the limit and window in ms.
// Supported units: min (60s), hour (3600s), day (86400s).
// If parsing fails, returns a default of 60 requests per 60000ms (1 minute).
func parseRateLimit(rate string) (int, int) {
	// Remove surrounding quotes if present
	rate = strings.Trim(rate, "\"'")
	parts := strings.SplitN(rate, "/", 2)
	if len(parts) != 2 {
		return 60, 60000
	}
	limit, err := strconv.Atoi(strings.TrimSpace(parts[0]))
	if err != nil {
		return 60, 60000
	}
	unit := strings.TrimSpace(parts[1])
	switch unit {
	case "min":
		return limit, 60 * 1000
	case "hour":
		return limit, 60 * 60 * 1000
	case "day":
		return limit, 24 * 60 * 60 * 1000
	default:
		return limit, 60 * 1000
	}
}

// extractResource extracts the resource name from an endpoint path.
// e.g. "/api/watermark" -> "watermark", "/api/jobs/:id" -> "jobs"
func extractResource(path string) string {
	parts := strings.Split(strings.TrimPrefix(path, "/"), "/")
	for _, p := range parts {
		if p == "api" || p == "" {
			continue
		}
		if strings.HasPrefix(p, ":") {
			continue
		}
		return p
	}
	if len(parts) > 0 {
		return parts[len(parts)-1]
	}
	return "root"
}

// isIdentRune returns true if r is valid in an identifier.
func isIdentRune(r rune) bool {
	return unicode.IsLetter(r) || unicode.IsDigit(r) || r == '_'
}

// extractInjectedVars scans middleware stmts for inject(val, name) calls
// and returns the set of injected variable names (e.g., {"auth": true}).
func extractInjectedVars(stmts []ast.ArrowStmt) map[string]bool {
	result := make(map[string]bool)
	for _, s := range stmts {
		if step, ok := s.(*ast.StepStmt); ok {
			if fn, ok := step.Expr.(*ast.FnCall); ok && fn.Name == "inject" && len(fn.Args) >= 2 {
				if ident, ok := fn.Args[1].(*ast.Ident); ok {
					result[ident.Name] = true
				}
			}
		}
	}
	return result
}

// extractInjectedModelMap scans middleware stmts and returns a mapping from
// model name to injected context variable name.
// E.g., if middleware has: key = query api_key ... ; inject key as auth
// then the result is {"api_key": "auth"}.
func extractInjectedModelMap(stmts []ast.ArrowStmt) map[string]string {
	// First pass: find bindings that come from data ops (query/fetch)
	// binding_name -> model_name
	bindingModel := make(map[string]string)
	for _, s := range stmts {
		if step, ok := s.(*ast.StepStmt); ok && step.Binding != "" {
			if fn, ok := step.Expr.(*ast.FnCall); ok && isDataOp(fn.Name) && len(fn.Args) > 0 {
				if ident, ok := fn.Args[0].(*ast.Ident); ok {
					bindingModel[step.Binding] = ident.Name
				}
			}
		}
	}

	// Second pass: find inject calls and resolve their source binding to model
	result := make(map[string]string)
	for _, s := range stmts {
		if step, ok := s.(*ast.StepStmt); ok {
			if fn, ok := step.Expr.(*ast.FnCall); ok && fn.Name == "inject" && len(fn.Args) >= 2 {
				if srcIdent, ok := fn.Args[0].(*ast.Ident); ok {
					if nameIdent, ok := fn.Args[1].(*ast.Ident); ok {
						if modelName, exists := bindingModel[srcIdent.Name]; exists {
							result[modelName] = nameIdent.Name
						}
					}
				}
			}
		}
	}
	return result
}

// isDataOp checks if a function name is a Blueprint data operation.
func isDataOp(name string) bool {
	switch name {
	case "query", "save", "fetch", "update", "delete", "count", "seed":
		return true
	}
	return false
}

// isPathParam checks if a parameter name appears as :name in the URL path.
func isPathParam(name, path string) bool {
	return strings.Contains(path, ":"+name)
}

// dataOpToJS converts a data operation FnCall to Drizzle ORM JavaScript code.
func dataOpToJS(v *ast.FnCall) string {
	return dataOpToJSWithCtx(v, nil)
}

// dataOpToJSWithCtx converts a data operation FnCall to Drizzle ORM JavaScript code,
// using context to resolve bound variable names for WHERE clauses.
func dataOpToJSWithCtx(v *ast.FnCall, ctx *emitCtx) string {
	if len(v.Args) == 0 {
		return "/* data op: missing model */"
	}

	modelName := ""
	if ident, ok := v.Args[0].(*ast.Ident); ok {
		modelName = ident.Name
	} else {
		return fmt.Sprintf("/* data op %s: unexpected first arg */", v.Name)
	}

	schemaTable := "schema." + toCamelCase(modelName)

	switch v.Name {
	case "fetch":
		// fetch model(id) -> (await db.select().from(schema.model).where(eq(schema.model.id, id)))[0]
		if len(v.Args) >= 2 {
			idExpr := exprToJSWithCtx(v.Args[1], ctx)
			return fmt.Sprintf("(await db.select().from(%s).where(eq(%s.id, %s)))[0]",
				schemaTable, schemaTable, idExpr)
		}
		return fmt.Sprintf("(await db.select().from(%s))[0]", schemaTable)

	case "save", "seed":
		// save model { fields } -> (await db.insert(schema.model).values({ fields }).returning())[0]
		if len(v.Args) >= 2 {
			if block, ok := v.Args[1].(*ast.BlockExpr); ok {
				vals := exprToJSWithCtx(block, ctx)
				return fmt.Sprintf("(await db.insert(%s).values(%s).returning())[0]",
					schemaTable, vals)
			}
		}
		return fmt.Sprintf("(await db.insert(%s).values({}).returning())[0]", schemaTable)

	case "update":
		// update model { fields } -> await db.update(schema.model).set({ fields }).where(eq(schema.model.id, boundVar.id))
		// Use the bound variable for the model if available in context
		idRef := "id"
		if ctx != nil && ctx.boundVars != nil {
			if boundVar, ok := ctx.boundVars[modelName]; ok {
				idRef = boundVar + ".id"
			}
		}
		if len(v.Args) >= 2 {
			if block, ok := v.Args[1].(*ast.BlockExpr); ok {
				vals := exprToJSWithCtx(block, ctx)
				return fmt.Sprintf("await db.update(%s).set(%s).where(eq(%s.id, %s))",
					schemaTable, vals, schemaTable, idRef)
			}
		}
		return fmt.Sprintf("await db.update(%s).set({})", schemaTable)

	case "delete":
		// delete <var> -> bulk or single delete depending on whether the variable is a collection
		if ctx != nil && ctx.varModels != nil {
			// The first arg might be a variable name (not a model name) for "delete old" style
			if ident, ok := v.Args[0].(*ast.Ident); ok {
				varName := toCamelCase(ident.Name)
				if _, isVar := ctx.varModels[varName]; isVar {
					// It's a collection variable — generate bulk delete
					return fmt.Sprintf("await db.delete(%s).where(inArray(%s.id, %s.map((r: any) => r.id)))",
						schemaTable, schemaTable, varName)
				}
			}
		}
		// delete model { ... } with boundVars -> single record delete
		idRef := "id"
		if ctx != nil && ctx.boundVars != nil {
			if boundVar, ok := ctx.boundVars[modelName]; ok {
				idRef = boundVar + ".id"
			}
		}
		return fmt.Sprintf("await db.delete(%s).where(eq(%s.id, %s))",
			schemaTable, schemaTable, idRef)

	case "query":
		return queryToJSWithCtx(v, schemaTable, ctx)

	case "count":
		return fmt.Sprintf("Number((await db.select({value: sql`count(*)`}).from(%s))[0].value)",
			schemaTable)
	}

	return "/* unknown data op */"
}

// queryToJS converts a query data operation to Drizzle ORM code.
func queryToJS(v *ast.FnCall, schemaTable string) string {
	return queryToJSWithCtx(v, schemaTable, nil)
}

// queryToJSWithCtx converts a query data operation to Drizzle ORM code with context.
// Handles structured FnCall markers for where/order/paginate from the parser.
func queryToJSWithCtx(v *ast.FnCall, schemaTable string, ctx *emitCtx) string {
	args := v.Args[1:] // skip model name

	// Extract structured markers (where/order/paginate FnCall nodes) from args
	var whereMarker *ast.FnCall
	var orderMarker *ast.FnCall
	var paginateMarker *ast.FnCall
	hasFirst := false
	var otherArgs []ast.Expr

	for _, arg := range args {
		if fn, ok := arg.(*ast.FnCall); ok {
			switch fn.Name {
			case "where":
				whereMarker = fn
				continue
			case "order":
				orderMarker = fn
				continue
			case "paginate":
				paginateMarker = fn
				continue
			}
		}
		if ident, ok := arg.(*ast.Ident); ok && ident.Name == "first" {
			hasFirst = true
			continue
		}
		otherArgs = append(otherArgs, arg)
	}

	// Build base query
	var query strings.Builder
	query.WriteString("db.select().from(" + schemaTable + ")")

	// Add where clause from marker
	if whereMarker != nil {
		if len(whereMarker.Args) == 1 {
			cond := whereMarker.Args[0]
			if _, ok := cond.(*ast.BinaryExpr); ok {
				query.WriteString(".where(" + whereExprToJSWithCtx(cond, schemaTable, ctx) + ")")
			} else if ident, ok := cond.(*ast.Ident); ok {
				// Filter variable (e.g., where(filters)) — convert object entries to Drizzle conditions
				filterVar := toCamelCase(ident.Name)
				query.WriteString(fmt.Sprintf(".where(and(...Object.entries(%s).map(([k, v]) => eq((%s as any)[k], v))))", filterVar, schemaTable))
			} else {
				query.WriteString(".where(" + exprToJSWithCtx(cond, ctx) + ")")
			}
		} else if len(whereMarker.Args) > 1 {
			conditions := make([]string, len(whereMarker.Args))
			for i, cond := range whereMarker.Args {
				conditions[i] = whereExprToJSWithCtx(cond, schemaTable, ctx)
			}
			query.WriteString(".where(and(" + strings.Join(conditions, ", ") + "))")
		}
	}

	// Add order clause from marker
	if orderMarker != nil && len(orderMarker.Args) >= 1 {
		field := exprToString(orderMarker.Args[0])
		direction := "desc" // default
		if len(orderMarker.Args) >= 2 {
			direction = exprToString(orderMarker.Args[1])
		}
		query.WriteString(fmt.Sprintf(".orderBy(%s(%s.%s))", direction, schemaTable, toCamelCase(field)))
	}

	// Handle paginate marker -> return {items, total} shape
	if paginateMarker != nil && len(paginateMarker.Args) >= 2 {
		page := exprToJSWithCtx(paginateMarker.Args[0], ctx)
		perPage := exprToJSWithCtx(paginateMarker.Args[1], ctx)
		baseQuery := query.String()
		whereClause := ""
		if whereMarker != nil {
			// Re-build just the where part for the count query
			var wq strings.Builder
			if len(whereMarker.Args) == 1 {
				cond := whereMarker.Args[0]
				if _, ok := cond.(*ast.BinaryExpr); ok {
					wq.WriteString(".where(" + whereExprToJSWithCtx(cond, schemaTable, ctx) + ")")
				} else if ident, ok := cond.(*ast.Ident); ok {
					filterVar := toCamelCase(ident.Name)
					wq.WriteString(fmt.Sprintf(".where(and(...Object.entries(%s).map(([k, v]) => eq((%s as any)[k], v))))", filterVar, schemaTable))
				} else {
					wq.WriteString(".where(" + exprToJSWithCtx(cond, ctx) + ")")
				}
			} else if len(whereMarker.Args) > 1 {
				conditions := make([]string, len(whereMarker.Args))
				for i, cond := range whereMarker.Args {
					conditions[i] = whereExprToJSWithCtx(cond, schemaTable, ctx)
				}
				wq.WriteString(".where(and(" + strings.Join(conditions, ", ") + "))")
			}
			whereClause = wq.String()
		}
		return fmt.Sprintf(
			"await (async () => { const _items = await %s.limit(%s).offset((%s - 1) * %s); const [{value: _ct}] = await db.select({value: sql`count(*)`}).from(%s)%s; return { items: _items, total: Number(_ct) }; })()",
			baseQuery, perPage, page, perPage, schemaTable, whereClause)
	}

	// Legacy fallback: if there are exactly 2 remaining non-marker args, treat as paginate(page, perPage)
	if len(otherArgs) == 2 && whereMarker == nil {
		page := exprToJSWithCtx(otherArgs[0], ctx)
		perPage := exprToJSWithCtx(otherArgs[1], ctx)
		baseQuery := query.String()
		return fmt.Sprintf(
			"await (async () => { const _items = await %s.limit(%s).offset((%s - 1) * %s); const [{value: _ct}] = await db.select({value: sql`count(*)`}).from(%s); return { items: _items, total: Number(_ct) }; })()",
			baseQuery, perPage, page, perPage, schemaTable)
	}

	// Legacy fallback: single remaining ident arg could be a filter object
	if len(otherArgs) == 1 && whereMarker == nil {
		query.Reset()
		query.WriteString("db.select().from(" + schemaTable + ")")
		query.WriteString(".where(" + exprToJSWithCtx(otherArgs[0], ctx) + ")")
	}

	if hasFirst {
		return fmt.Sprintf("(await %s)[0]", query.String())
	}

	return "await " + query.String()
}

// whereExprToJS converts a where condition expression to Drizzle ORM filter code.
func whereExprToJS(cond ast.Expr, schemaTable string) string {
	return whereExprToJSWithCtx(cond, schemaTable, nil)
}

// whereExprToJSWithCtx converts a where condition expression to Drizzle ORM filter code with context.
func whereExprToJSWithCtx(cond ast.Expr, schemaTable string, ctx *emitCtx) string {
	if bin, ok := cond.(*ast.BinaryExpr); ok {
		// Check if left side is a simple field reference (Ident)
		if ident, ok := bin.Left.(*ast.Ident); ok {
			field := toCamelCase(ident.Name)
			right := exprToJSWithCtx(bin.Right, ctx)
			switch bin.Op {
			case "==":
				return fmt.Sprintf("eq(%s.%s, %s)", schemaTable, field, right)
			case "!=":
				return fmt.Sprintf("ne(%s.%s, %s)", schemaTable, field, right)
			case "<":
				return fmt.Sprintf("lt(%s.%s, %s)", schemaTable, field, right)
			case ">":
				return fmt.Sprintf("gt(%s.%s, %s)", schemaTable, field, right)
			case "<=":
				return fmt.Sprintf("lte(%s.%s, %s)", schemaTable, field, right)
			case ">=":
				return fmt.Sprintf("gte(%s.%s, %s)", schemaTable, field, right)
			}
		}
	}
	// Fallback to generic expression
	return exprToJSWithCtx(cond, ctx)
}

// isDurationField checks if a field name is a duration unit (used for N.days, N.hours patterns).
func isDurationField(field string) bool {
	switch field {
	case "ms", "s", "sec", "seconds", "min", "minutes", "hour", "hours", "day", "days":
		return true
	}
	return false
}

// durationFieldToMS converts a numeric literal + duration unit to milliseconds expression.
func durationFieldToMS(num, unit string) string {
	switch unit {
	case "ms":
		return num
	case "s", "sec", "seconds":
		return fmt.Sprintf("(%s * 1000)", num)
	case "min", "minutes":
		return fmt.Sprintf("(%s * 60000)", num)
	case "hour", "hours":
		return fmt.Sprintf("(%s * 3600000)", num)
	case "day", "days":
		return fmt.Sprintf("(%s * 86400000)", num)
	}
	return num
}

// isBuiltinFn checks if a function name is a Blueprint built-in (not a user-defined function).
// This includes language keywords and query DSL functions that appear as FnCall nodes.
func isBuiltinFn(name string) bool {
	switch name {
	case "log", "clock", "sleep", "inject", "map", "pipe",
		"where", "order", "paginate", "limit", "offset":
		return true
	}
	return false
}

// transformInterpolation applies Blueprint-to-JS transformations on string
// interpolation bodies. For example, `.count` becomes `.length` in JavaScript.
func transformInterpolation(s string) string {
	return strings.ReplaceAll(s, ".count", ".length")
}

// normalizeServiceName converts an external service name to a canonical underscore form
// for use with toCamelCase/toPascalCase. Strips surrounding quotes, replaces hyphens
// with underscores, then lower-cases so that "auth-service", auth_service, and
// "Auth-Service" all resolve to the same camelCase identifier (authService).
func normalizeServiceName(name string) string {
	name = strings.Trim(name, `"`)
	name = strings.ToLower(name)
	name = strings.ReplaceAll(name, "-", "_")
	return name
}

// walkExpr recursively visits all sub-expressions of e, calling fn for each.
func walkExpr(e ast.Expr, fn func(ast.Expr)) {
	if e == nil {
		return
	}
	fn(e)
	switch v := e.(type) {
	case *ast.BinaryExpr:
		walkExpr(v.Left, fn)
		walkExpr(v.Right, fn)
	case *ast.UnaryExpr:
		walkExpr(v.Operand, fn)
	case *ast.ParenExpr:
		walkExpr(v.Expr, fn)
	case *ast.FnCall:
		for _, arg := range v.Args {
			walkExpr(arg, fn)
		}
	case *ast.FieldAccess:
		walkExpr(v.Base, fn)
	case *ast.IndexAccess:
		walkExpr(v.Base, fn)
		walkExpr(v.Index, fn)
	case *ast.ListExpr:
		for _, el := range v.Elements {
			walkExpr(el, fn)
		}
	case *ast.BlockExpr:
		for _, kv := range v.Entries {
			walkExpr(kv.Value, fn)
		}
	}
}

// walkStmts visits all expressions in a list of arrow statements.
func walkStmts(stmts []ast.ArrowStmt, fn func(ast.Expr)) {
	for _, stmt := range stmts {
		switch s := stmt.(type) {
		case *ast.StepStmt:
			walkExpr(s.Expr, fn)
		case *ast.GuardStmt:
			walkExpr(s.Condition, fn)
		case *ast.WhenStmt:
			walkExpr(s.Condition, fn)
			if s.Inline != nil {
				walkExpr(s.Inline, fn)
			}
			walkStmts(s.Body, fn)
		case *ast.OutputStmt:
			walkExpr(s.Value, fn)
		case *ast.TryRecover:
			walkStmts(s.Try, fn)
			walkStmts(s.Recover, fn)
		}
	}
}
