package js

import (
	"fmt"
	"strings"

	"github.com/abdul-hamid-achik/blueprint/internal/ast"
	"github.com/abdul-hamid-achik/blueprint/internal/codegen"
)

// --- Static files ---

func (g *Generator) genPackageJSON(bp *ast.Blueprint, hasDB, hasCache, hasStorage, hasQueue, hasEndpoints, hasWS bool) codegen.OutputFile {
	name := bp.Name

	deps := map[string]string{
		"hono":              "^4.6.0",
		"@hono/node-server": "^1.13.0",
		"zod":               "^3.23.0",
		"dotenv":            "^16.4.0",
	}
	if hasEndpoints {
		deps["@hono/zod-validator"] = "^0.4.2"
	}
	if hasDB {
		deps["drizzle-orm"] = "^0.45.2"
		deps["pg"] = "^8.13.0"
	}
	if hasCache {
		// bullmq@5.30+ peer-requires redis>=5.0.0; keep these in lockstep
		// so `npm install` on a generated project doesn't ERESOLVE.
		deps["redis"] = "^5.0.0"
	}
	if hasStorage {
		deps["@aws-sdk/client-s3"] = "^3.700.0"
	}
	if hasQueue {
		deps["bullmq"] = "^5.30.0"
	}
	if hasWS {
		deps["@hono/node-ws"] = "^1.0.0"
	}
	if g.reactQuery {
		deps["@tanstack/react-query"] = "^5.59.20"
		deps["react"] = "^18.3.1"
	}

	devDeps := map[string]string{
		"typescript":  "^5.7.0",
		"tsx":         "^4.19.0",
		"@types/node": "^22.0.0",
		"@types/pg":   "^8.11.0",
		"vitest":      "^4.1.10",
	}
	if hasDB {
		devDeps["drizzle-kit"] = "^0.31.10"
	}
	if (g.genTests || g.propertyTests) && hasDB {
		devDeps["@electric-sql/pglite"] = "^0.2.0"
	}
	if g.propertyTests {
		devDeps["fast-check"] = "^3.23.2"
	}
	if g.reactQuery {
		devDeps["@types/react"] = "^18.3.12"
	}

	var b strings.Builder
	b.WriteString("{\n")
	fmt.Fprintf(&b, "  \"name\": %s,\n", fmt.Sprintf("%q", name))
	b.WriteString(`  "version": "0.1.0",` + "\n")
	b.WriteString(`  "private": true,` + "\n")
	b.WriteString(`  "type": "module",` + "\n")
	b.WriteString(`  "scripts": {` + "\n")
	fmt.Fprintf(&b, `    "start": "tsx src/index.ts",`+"\n")
	fmt.Fprintf(&b, `    "dev": "tsx watch src/index.ts",`+"\n")
	b.WriteString(`    "build": "tsc",` + "\n")
	b.WriteString(`    "test": "vitest run",` + "\n")
	b.WriteString(`    "test:watch": "vitest"` + "\n")
	b.WriteString("  },\n")

	// Dependencies — sorted for deterministic output
	b.WriteString(`  "dependencies": {` + "\n")
	depKeys := sortedKeys(deps)
	for i, k := range depKeys {
		comma := ","
		if i == len(depKeys)-1 {
			comma = ""
		}
		fmt.Fprintf(&b, `    "%s": "%s"%s`+"\n", k, deps[k], comma)
	}
	b.WriteString("  },\n")

	// Dev dependencies — sorted for deterministic output
	b.WriteString(`  "devDependencies": {` + "\n")
	devKeys := sortedKeys(devDeps)
	for i, k := range devKeys {
		comma := ","
		if i == len(devKeys)-1 {
			comma = ""
		}
		fmt.Fprintf(&b, `    "%s": "%s"%s`+"\n", k, devDeps[k], comma)
	}
	b.WriteString("  }\n")
	b.WriteString("}\n")

	return codegen.OutputFile{Path: "package.json", Content: []byte(b.String())}
}

func (g *Generator) genTSConfig() codegen.OutputFile {
	content := `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "NodeNext",
    "moduleResolution": "nodenext",
    "esModuleInterop": true,
    "strict": true,
    "outDir": "dist",
    "rootDir": "src",
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "resolveJsonModule": true,
    "declaration": true,
    "declarationMap": true,
    "sourceMap": true
  },
  "include": ["src/**/*.ts"],
  "exclude": ["node_modules", "dist", "test"]
}
`
	return codegen.OutputFile{Path: "tsconfig.json", Content: []byte(content)}
}

func (g *Generator) genEnvExample(secrets []*ast.Secret, envs []*ast.Env, extraEnvVars ...string) codegen.OutputFile {
	var b strings.Builder
	b.WriteString("# Generated by Blueprint — fill in your values\n\n")
	declared := make(map[string]bool)
	wroteInfraLine := false
	for _, s := range secrets {
		declared[s.Name] = true
		fmt.Fprintf(&b, "%s=\n", s.Name)
		wroteInfraLine = true
	}
	// Seed the dedupe set with user env declarations BEFORE adding extra
	// infra vars so a user `env DATABASE_URL { ... }` doesn't produce a
	// duplicate line in .env.example.
	for _, e := range envs {
		declared[e.Name] = true
	}
	// Extra infra env vars (e.g., REDIS_URL, DATABASE_URL) that aren't already
	// declared as secrets or envs — keep .env.example in sync with env.ts.
	for _, name := range extraEnvVars {
		if declared[name] {
			continue
		}
		declared[name] = true
		fmt.Fprintf(&b, "%s=\n", name)
		wroteInfraLine = true
	}
	if wroteInfraLine && len(envs) > 0 {
		b.WriteString("\n")
	}
	for _, e := range envs {
		val := exprToString(e.Value)
		fmt.Fprintf(&b, "%s=%s\n", e.Name, val)
	}
	return codegen.OutputFile{Path: ".env.example", Content: []byte(b.String())}
}

func (g *Generator) genEnvTS(secrets []*ast.Secret, envs []*ast.Env, extraEnvVars ...string) codegen.OutputFile {
	var b strings.Builder
	b.WriteString(fileHeader(g.sourceFile))
	b.WriteString("import { z } from 'zod';\nimport 'dotenv/config';\n\n")
	b.WriteString("const envSchema = z.object({\n")

	// Track which env vars are already declared by secrets/envs to avoid duplicates
	declared := make(map[string]bool)
	for _, s := range secrets {
		declared[s.Name] = true
		req := ".optional()"
		if s.Required {
			req = ""
		}
		fmt.Fprintf(&b, "  %s: z.string()%s,\n", s.Name, req)
	}
	// Seed the dedupe set with user env declarations BEFORE adding extra
	// infra vars (REDIS_URL, DATABASE_URL, ...) so a user `env DATABASE_URL
	// { ... }` is not also emitted as a bare z.string(), producing a
	// duplicate key (TS1117).
	for _, e := range envs {
		declared[e.Name] = true
	}
	for _, name := range extraEnvVars {
		if !declared[name] {
			declared[name] = true
			fmt.Fprintf(&b, "  %s: z.string(),\n", name)
		}
	}
	for _, e := range envs {
		zodType := "z.string()"
		defaultVal := exprToJS(e.Value)
		switch e.Value.(type) {
		case *ast.IntLit, *ast.FloatLit, *ast.SizeLit:
			zodType = "z.coerce.number()"
		case *ast.ListExpr:
			// List env vars: store as JSON string, parse on load
			zodType = "z.string().transform((v: string) => v.split(','))"
			// Convert list to comma-separated string default
			list := e.Value.(*ast.ListExpr)
			parts := make([]string, len(list.Elements))
			for i, el := range list.Elements {
				parts[i] = exprToString(el)
			}
			defaultVal = fmt.Sprintf(`"%s"`, strings.Join(parts, ","))
		case *ast.BinaryExpr:
			// Arithmetic expressions in env defaults are numeric
			zodType = "z.coerce.number()"
		case *ast.StringLit:
			// String default needs to be quoted
			defaultVal = fmt.Sprintf(`"%s"`, exprToString(e.Value))
		}
		fmt.Fprintf(&b, "  %s: %s.default(%s),\n", e.Name, zodType, defaultVal)
	}
	b.WriteString("});\n\n")
	b.WriteString("export const env = envSchema.parse(process.env);\n")

	return codegen.OutputFile{Path: "src/lib/env.ts", Content: []byte(b.String())}
}

func (g *Generator) genErrors() codegen.OutputFile {
	var b strings.Builder
	b.WriteString(fileHeader(g.sourceFile))
	b.WriteString(`import type { ContentfulStatusCode } from 'hono/utils/http-status';

export class BpError extends Error {
  constructor(
    public statusCode: ContentfulStatusCode,
    message: string,
  ) {
    super(message);
    this.name = 'BpError';
  }
}

export class ValidationError extends BpError {
  constructor(message: string) {
    super(400, message);
    this.name = 'ValidationError';
  }
}

export class AuthError extends BpError {
  constructor(message: string) {
    super(401, message);
    this.name = 'AuthError';
  }
}

export class NotFoundError extends BpError {
  constructor(message: string) {
    super(404, message);
    this.name = 'NotFoundError';
  }
}
`)
	return codegen.OutputFile{Path: "src/lib/errors.ts", Content: []byte(b.String())}
}

func (g *Generator) genI18n(locales []*ast.Locale, translations []*ast.Translation) codegen.OutputFile {
	var b strings.Builder
	b.WriteString(fileHeader(g.sourceFile))
	b.WriteString("export const locales = [")
	for i, loc := range locales {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(&b, "%q", loc.Code)
	}
	b.WriteString("] as const;\n")
	defaultLocale := ""
	for _, loc := range locales {
		if loc.Default {
			defaultLocale = loc.Code
			break
		}
	}
	if defaultLocale == "" && len(locales) > 0 {
		defaultLocale = locales[0].Code
	}
	fmt.Fprintf(&b, "export const defaultLocale = %q;\n", defaultLocale)
	fallbackParts := make([]string, 0, len(locales))
	for _, loc := range locales {
		fallback := loc.Fallback
		if fallback == "" {
			fallback = loc.Code
		}
		fallbackParts = append(fallbackParts, fmt.Sprintf("%q: %q", loc.Code, fallback))
	}
	fmt.Fprintf(&b, "export const localeFallbacks = { %s } as const;\n", strings.Join(fallbackParts, ", "))
	namespaceParts := make([]string, 0, len(translations))
	valueParts := make([]string, 0, len(translations))
	for _, tr := range translations {
		var keyParts []string
		for _, key := range tr.Keys {
			keyParts = append(keyParts, fmt.Sprintf("%q", key))
		}
		namespaceParts = append(namespaceParts, fmt.Sprintf("%s: [%s]", toCamelCase(tr.Name), strings.Join(keyParts, ", ")))
		bundleParts := make([]string, 0, len(tr.Bundles))
		for _, bundle := range tr.Bundles {
			localized := make([]string, 0, len(bundle.Values))
			for _, kv := range bundle.Values {
				localized = append(localized, fmt.Sprintf("%q: %s", kv.Key, exprToJS(kv.Value)))
			}
			bundleParts = append(bundleParts, fmt.Sprintf("%q: { %s }", bundle.Locale, strings.Join(localized, ", ")))
		}
		valueParts = append(valueParts, fmt.Sprintf("%s: { %s }", toCamelCase(tr.Name), strings.Join(bundleParts, ", ")))
	}
	fmt.Fprintf(&b, "export const translationNamespaces = { %s } as const;\n", strings.Join(namespaceParts, ", "))
	fmt.Fprintf(&b, "export const translationValues = { %s } as const;\n", strings.Join(valueParts, ", "))
	b.WriteString("export type LocaleCode = (typeof locales)[number];\n")
	b.WriteString("export type TranslationNamespace = keyof typeof translationNamespaces;\n")
	return codegen.OutputFile{Path: "src/lib/i18n.ts", Content: []byte(b.String())}
}

func (g *Generator) genStateLib(states []*ast.StateMachine) codegen.OutputFile {
	var b strings.Builder
	b.WriteString(fileHeader(g.sourceFile))
	b.WriteString("export class InvalidTransitionError extends Error {\n")
	b.WriteString("  constructor(public machine: string, public from: string, public to: string) {\n")
	b.WriteString("    super(`Invalid transition for ${machine}: ${from} -> ${to}`);\n")
	b.WriteString("    this.name = 'InvalidTransitionError';\n")
	b.WriteString("  }\n")
	b.WriteString("}\n\n")
	for _, sm := range states {
		name := toPascalCase(sm.Name)
		parts := make([]string, 0, len(sm.States))
		for _, state := range sm.States {
			nexts := make([]string, 0)
			for _, tr := range sm.Transitions {
				if tr.From == state {
					nexts = append(nexts, fmt.Sprintf("%q", tr.To))
				}
			}
			parts = append(parts, fmt.Sprintf("  %s: [%s]", state, strings.Join(nexts, ", ")))
		}
		fmt.Fprintf(&b, "export const %sTransitions = {\n%s\n} as const;\n", name, strings.Join(parts, ",\n"))
		fmt.Fprintf(&b, "export function canTransition%s(from: string, to: string): boolean {\n", name)
		fmt.Fprintf(&b, "  return ((%sTransitions as any)[from] ?? []).includes(to);\n", name)
		b.WriteString("}\n")
		fmt.Fprintf(&b, "export function transition%s<T extends string>(from: T, to: T): T {\n", name)
		fmt.Fprintf(&b, "  if (!canTransition%s(from, to)) throw new InvalidTransitionError(%q, from, to);\n", name, sm.Name)
		b.WriteString("  return to;\n")
		b.WriteString("}\n\n")
	}
	return codegen.OutputFile{Path: "src/lib/state.ts", Content: []byte(b.String())}
}

func (g *Generator) genAnalyticsLib(analytics []*ast.Analytics) codegen.OutputFile {
	var b strings.Builder
	b.WriteString(fileHeader(g.sourceFile))
	namespaceParts := make([]string, 0, len(analytics))
	sinkParts := make([]string, 0, len(analytics))
	for _, a := range analytics {
		events := make([]string, len(a.Events))
		for i, event := range a.Events {
			events[i] = fmt.Sprintf("%q", event)
		}
		namespaceParts = append(namespaceParts, fmt.Sprintf("%s: [%s]", toCamelCase(a.Name), strings.Join(events, ", ")))
		sinks := make([]string, len(a.Sinks))
		for i, sink := range a.Sinks {
			if sink.Target != nil {
				sinks[i] = fmt.Sprintf("{ kind: %q, target: %s }", sink.Kind, exprToJS(sink.Target))
			} else {
				sinks[i] = fmt.Sprintf("{ kind: %q }", sink.Kind)
			}
		}
		sinkParts = append(sinkParts, fmt.Sprintf("%s: [%s]", toCamelCase(a.Name), strings.Join(sinks, ", ")))
	}
	fmt.Fprintf(&b, "export const analyticsNamespaces = { %s } as const;\n", strings.Join(namespaceParts, ", "))
	fmt.Fprintf(&b, "export const analyticsSinks = { %s } as const;\n", strings.Join(sinkParts, ", "))
	b.WriteString("export type AnalyticsNamespace = keyof typeof analyticsNamespaces;\n")
	b.WriteString("const analyticsBatchSize = 25;\n")
	b.WriteString("const analyticsFlushMs = 2000;\n")
	b.WriteString("const analyticsMaxRetries = 3;\n")
	b.WriteString("const analyticsQueues = new Map<string, Array<{ namespace: AnalyticsNamespace; event: string; payload: unknown; at: string }>>();\n")
	b.WriteString("const analyticsTimers = new Map<string, ReturnType<typeof setTimeout>>();\n\n")
	b.WriteString("async function sleep(ms: number): Promise<void> {\n  await new Promise((resolve) => setTimeout(resolve, ms));\n}\n\n")
	b.WriteString("async function sendAnalyticsBatch(target: string, batch: Array<{ namespace: AnalyticsNamespace; event: string; payload: unknown; at: string }>): Promise<void> {\n")
	b.WriteString("  let lastError: unknown;\n")
	b.WriteString("  for (let attempt = 0; attempt < analyticsMaxRetries; attempt++) {\n")
	b.WriteString("    try {\n")
	b.WriteString("      const response = await fetch(target, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ events: batch }) });\n")
	b.WriteString("      if (!response.ok) throw new Error(`Analytics sink failed: ${response.status}`);\n")
	b.WriteString("      return;\n")
	b.WriteString("    } catch (error) {\n")
	b.WriteString("      lastError = error;\n")
	b.WriteString("      await sleep((attempt + 1) * 500);\n")
	b.WriteString("    }\n")
	b.WriteString("  }\n")
	b.WriteString("  throw lastError instanceof Error ? lastError : new Error(String(lastError));\n")
	b.WriteString("}\n\n")
	b.WriteString("async function flushAnalyticsTarget(target: string): Promise<void> {\n")
	b.WriteString("  const batch = analyticsQueues.get(target) ?? [];\n")
	b.WriteString("  if (batch.length === 0) return;\n")
	b.WriteString("  analyticsQueues.set(target, []);\n")
	b.WriteString("  const timer = analyticsTimers.get(target);\n")
	b.WriteString("  if (timer) { clearTimeout(timer); analyticsTimers.delete(target); }\n")
	b.WriteString("  await sendAnalyticsBatch(target, batch);\n")
	b.WriteString("}\n\n")
	b.WriteString("function queueAnalytics(target: string, item: { namespace: AnalyticsNamespace; event: string; payload: unknown; at: string }): void {\n")
	b.WriteString("  const queue = analyticsQueues.get(target) ?? [];\n")
	b.WriteString("  queue.push(item);\n")
	b.WriteString("  analyticsQueues.set(target, queue);\n")
	b.WriteString("  if (queue.length >= analyticsBatchSize) {\n")
	b.WriteString("    void flushAnalyticsTarget(target);\n")
	b.WriteString("    return;\n")
	b.WriteString("  }\n")
	b.WriteString("  if (!analyticsTimers.has(target)) {\n")
	b.WriteString("    analyticsTimers.set(target, setTimeout(() => { void flushAnalyticsTarget(target); }, analyticsFlushMs));\n")
	b.WriteString("  }\n")
	b.WriteString("}\n\n")
	b.WriteString("export async function track(event: string, payload: unknown = {}): Promise<void> {\n")
	b.WriteString("  const namespaces = Object.entries(analyticsNamespaces).filter(([, events]) => (events as readonly string[]).includes(event)).map(([name]) => name as AnalyticsNamespace);\n")
	b.WriteString("  for (const namespace of namespaces) {\n")
	b.WriteString("    for (const sink of ((analyticsSinks as any)[namespace] ?? [])) {\n")
	b.WriteString("      switch (sink.kind) {\n")
	b.WriteString("        case 'console':\n")
	b.WriteString("          console.log(`[analytics:${namespace}] ${event}`, payload);\n")
	b.WriteString("          break;\n")
	b.WriteString("        case 'http':\n")
	b.WriteString("          queueAnalytics(String(sink.target), { namespace, event, payload, at: new Date().toISOString() });\n")
	b.WriteString("          break;\n")
	b.WriteString("      }\n")
	b.WriteString("    }\n")
	b.WriteString("  }\n")
	b.WriteString("}\n")
	return codegen.OutputFile{Path: "src/lib/analytics.ts", Content: []byte(b.String())}
}

func (g *Generator) genSaveMigrations(saves []*ast.SaveSchema) []codegen.OutputFile {
	var files []codegen.OutputFile
	var b strings.Builder
	b.WriteString(fileHeader(g.sourceFile))
	for _, save := range saves {
		imports := saveMigrationImports(save)
		for _, imp := range imports {
			fmt.Fprintf(&b, "import { %s } from %q;\n", imp.FuncName, imp.ModulePath)
		}
	}
	b.WriteString("\n")
	for _, save := range saves {
		name := toPascalCase(save.Name)
		versionField := toCamelCase(save.VersionField)
		fmt.Fprintf(&b, "export const %sSaveConfig = { model: %q, versionField: %q, latest: %d } as const;\n", toCamelCase(save.Name), save.Model, save.VersionField, save.Latest)
		fmt.Fprintf(&b, "export async function upgrade%sSave<T extends Record<string, any>>(save: T): Promise<T> {\n", name)
		b.WriteString("  let current: any = { ...save };\n")
		if save.Latest <= 1 {
			b.WriteString("  return current as T;\n")
			b.WriteString("}\n\n")
		} else {
			fmt.Fprintf(&b, "  let version = Number(current.%s ?? 1);\n", versionField)
			fmt.Fprintf(&b, "  while (version < %d) {\n", save.Latest)
			b.WriteString("    switch (version) {\n")
			for version := 1; version < save.Latest; version++ {
				fmt.Fprintf(&b, "      case %d:\n", version)
				fmt.Fprintf(&b, "        current = await migrate%sSaveFrom%dTo%d(current);\n", name, version, version+1)
				fmt.Fprintf(&b, "        version = %d;\n", version+1)
				fmt.Fprintf(&b, "        current.%s = %d;\n", versionField, version+1)
				b.WriteString("        break;\n")
			}
			b.WriteString("      default:\n        return current as T;\n")
			b.WriteString("    }\n")
			b.WriteString("  }\n")
			b.WriteString("  return current as T;\n")
			b.WriteString("}\n\n")
		}

		files = append(files, saveMigrationStubs(g.sourceFile, save)...)
	}
	files = append(files, codegen.OutputFile{Path: "src/lib/save-migrations.ts", Content: []byte(b.String())})
	return files
}

type saveMigrationImport struct {
	FuncName   string
	ModulePath string
}

func saveMigrationImports(save *ast.SaveSchema) []saveMigrationImport {
	if save.Latest <= 1 {
		return nil
	}
	byStep := map[string]*ast.SaveMigration{}
	for _, mig := range save.Migrations {
		byStep[fmt.Sprintf("%d->%d", mig.From, mig.To)] = mig
	}
	imports := make([]saveMigrationImport, 0, save.Latest-1)
	for version := 1; version < save.Latest; version++ {
		funcName := fmt.Sprintf("migrate%sSaveFrom%dTo%d", toPascalCase(save.Name), version, version+1)
		modulePath := fmt.Sprintf("../saves/%s.js", toKebabCase(save.Name))
		if mig := byStep[fmt.Sprintf("%d->%d", version, version+1)]; mig != nil && mig.Module != "" {
			modulePath = saveMigrationModuleImport(mig.Module)
		}
		imports = append(imports, saveMigrationImport{FuncName: funcName, ModulePath: modulePath})
	}
	return imports
}

func saveMigrationModuleImport(module string) string {
	if strings.HasPrefix(module, "./") {
		module = "../saves/" + strings.TrimPrefix(module, "./")
	}
	if !strings.HasSuffix(module, ".js") {
		module += ".js"
	}
	return module
}

func saveMigrationStubs(sourceFile string, save *ast.SaveSchema) []codegen.OutputFile {
	if save.Latest <= 1 {
		return []codegen.OutputFile{{Path: fmt.Sprintf("src/saves/%s.ts", toKebabCase(save.Name)), Content: []byte(fileHeader(sourceFile) + "export {};\n")}}
	}
	byModule := map[string][]string{}
	for version := 1; version < save.Latest; version++ {
		stepKey := fmt.Sprintf("%d->%d", version, version+1)
		funcName := fmt.Sprintf("migrate%sSaveFrom%dTo%d", toPascalCase(save.Name), version, version+1)
		modulePath := fmt.Sprintf("src/saves/%s.ts", toKebabCase(save.Name))
		for _, mig := range save.Migrations {
			if fmt.Sprintf("%d->%d", mig.From, mig.To) == stepKey && mig.Module != "" {
				modulePath = saveMigrationStubPath(mig.Module)
				break
			}
		}
		byModule[modulePath] = append(byModule[modulePath], funcName)
	}
	files := make([]codegen.OutputFile, 0, len(byModule))
	for path, funcs := range byModule {
		var stub strings.Builder
		fmt.Fprintf(&stub, "// Blueprint save migration implementation scaffold from %s.\n", sourceFile)
		stub.WriteString("// This file is user-owned; `bp build` will not overwrite it. Implement the migration functions below.\n\n")
		for _, fn := range funcs {
			fmt.Fprintf(&stub, "export async function %s(save: any): Promise<any> {\n", fn)
			stub.WriteString("  return save;\n")
			stub.WriteString("}\n\n")
		}
		files = append(files, codegen.OutputFile{
			Path:      path,
			Content:   []byte(stub.String()),
			UserOwned: true,
		})
	}
	return files
}

func saveMigrationStubPath(module string) string {
	module = strings.TrimPrefix(module, "./")
	if !strings.HasSuffix(module, ".ts") {
		module += ".ts"
	}
	return fmt.Sprintf("src/saves/%s", module)
}

func (g *Generator) genDB(bp *ast.Blueprint) codegen.OutputFile {
	var b strings.Builder
	b.WriteString(fileHeader(g.sourceFile))
	b.WriteString(`import { drizzle } from 'drizzle-orm/node-postgres';
import pg from 'pg';
import { env } from './env.js';
import * as schema from '../models/schema.js';

const pool = new pg.Pool({
  connectionString: env.DATABASE_URL,
});

export const db = drizzle(pool, { schema });
`)
	return codegen.OutputFile{Path: "src/lib/db.ts", Content: []byte(b.String())}
}

func (g *Generator) genStorage() codegen.OutputFile {
	var b strings.Builder
	b.WriteString(fileHeader(g.sourceFile))
	b.WriteString(`import { S3Client, PutObjectCommand, GetObjectCommand, DeleteObjectCommand } from '@aws-sdk/client-s3';
import { env } from './env.js';

const s3 = new S3Client({});

export async function upload(file: Buffer | ReadableStream, bucket: string, key?: string): Promise<{ url: string; key: string }> {
  const fileKey = key ?? crypto.randomUUID();
  await s3.send(new PutObjectCommand({ Bucket: bucket, Key: fileKey, Body: file as any }));
  return { url: ` + "`s3://${bucket}/${fileKey}`" + `, key: fileKey };
}

export async function download(bucket: string, key: string): Promise<ReadableStream> {
  const res = await s3.send(new GetObjectCommand({ Bucket: bucket, Key: key }));
  return res.Body as any;
}

export async function deleteS3Object(urlOrBucket: string, key?: string): Promise<void> {
  let bucket = urlOrBucket;
  let objectKey = key;
  if (!objectKey && urlOrBucket.startsWith('s3://')) {
    const parsed = new URL(urlOrBucket);
    bucket = parsed.hostname;
    objectKey = parsed.pathname.replace(/^\//, '');
  }
  if (!objectKey) {
    throw new Error('deleteS3Object requires a key or s3:// URL');
  }
  await s3.send(new DeleteObjectCommand({ Bucket: bucket, Key: objectKey }));
}

export async function deleteObject(bucket: string, key: string): Promise<void> {
  await s3.send(new DeleteObjectCommand({ Bucket: bucket, Key: key }));
}
`)
	return codegen.OutputFile{Path: "src/lib/storage.ts", Content: []byte(b.String())}
}

func (g *Generator) genCache() codegen.OutputFile {
	var b strings.Builder
	b.WriteString(fileHeader(g.sourceFile))
	b.WriteString(`import { createClient } from 'redis';
import { env } from './env.js';

export const redis = createClient({ url: env.REDIS_URL });
redis.on('error', (err) => console.error('Redis error:', err));

export async function connectCache(): Promise<void> {
  if (!redis.isOpen) await redis.connect();
}

export async function cached<T>(key: string, ttlSeconds: number, fn: () => Promise<T>): Promise<T> {
  await connectCache();
  const hit = await redis.get(key);
  if (hit) return JSON.parse(hit) as T;
  const result = await fn();
  await redis.setEx(key, ttlSeconds, JSON.stringify(result));
  return result;
}
`)
	return codegen.OutputFile{Path: "src/lib/cache.ts", Content: []byte(b.String())}
}

// --- Dockerfile ---

func (g *Generator) genDockerfile() codegen.OutputFile {
	port := blueprintEntryInt(g.file.Blueprint, "port")
	if port == 0 {
		port = 3000
	}
	content := fmt.Sprintf(`FROM oven/bun:1 AS builder
WORKDIR /app

COPY package.json bun.lock* ./
RUN bun install

COPY . .
RUN bun run build

FROM oven/bun:1
WORKDIR /app

COPY package.json bun.lock* ./
RUN bun install --production

COPY --from=builder /app/dist ./dist

RUN addgroup --system app && adduser --system --ingroup app app
USER app

EXPOSE %d
CMD ["bun", "dist/index.js"]
`, port)
	return codegen.OutputFile{Path: "Dockerfile", Content: []byte(content)}
}

// --- .gitignore ---

func (g *Generator) genGitignore() codegen.OutputFile {
	content := `node_modules/
dist/
frontend/node_modules/
frontend/dist/
.env
*.log
`
	return codegen.OutputFile{Path: ".gitignore", Content: []byte(content)}
}

// --- drizzle.config.ts ---

func (g *Generator) genDrizzleConfig() codegen.OutputFile {
	content := `import { defineConfig } from 'drizzle-kit';

export default defineConfig({
  schema: './src/models/schema.ts',
  out: './drizzle',
  dialect: 'postgresql',
  dbCredentials: {
    url: process.env.DATABASE_URL!,
  },
});
`
	return codegen.OutputFile{Path: "drizzle.config.ts", Content: []byte(content)}
}
