package js

import (
	"fmt"
	"strings"

	"github.com/abdul-hamid-achik/blueprint/internal/ast"
	"github.com/abdul-hamid-achik/blueprint/internal/codegen"
)

// --- Static files ---

func (g *Generator) genPackageJSON(bp *ast.Blueprint, hasDB, hasCache, hasStorage, hasQueue, hasEndpoints, hasWS bool) codegen.OutputFile {
	name := bp.Name
	port := blueprintEntryInt(bp, "port")
	if port == 0 {
		port = 3000
	}

	deps := map[string]string{
		"hono":              "^4.6.0",
		"@hono/node-server": "^1.13.0",
		"zod":               "^3.23.0",
		"dotenv":            "^16.4.0",
	}
	if hasEndpoints {
		deps["@hono/zod-validator"] = "^0.4.2"
	}
	if hasDB {
		deps["drizzle-orm"] = "^0.36.0"
		deps["pg"] = "^8.13.0"
	}
	if hasCache {
		deps["redis"] = "^4.7.0"
	}
	if hasStorage {
		deps["@aws-sdk/client-s3"] = "^3.700.0"
	}
	if hasQueue {
		deps["bullmq"] = "^5.30.0"
	}
	if hasWS {
		deps["@hono/node-ws"] = "^1.0.0"
	}

	devDeps := map[string]string{
		"typescript":  "^5.7.0",
		"tsx":         "^4.19.0",
		"@types/node": "^22.0.0",
		"@types/pg":   "^8.11.0",
		"vitest":      "^2.1.0",
	}
	if hasDB {
		devDeps["drizzle-kit"] = "^0.28.0"
	}

	var b strings.Builder
	b.WriteString("{\n")
	b.WriteString(fmt.Sprintf("  \"name\": %s,\n", fmt.Sprintf("%q", name)))
	b.WriteString(`  "version": "0.1.0",` + "\n")
	b.WriteString(`  "private": true,` + "\n")
	b.WriteString(`  "type": "module",` + "\n")
	b.WriteString(`  "scripts": {` + "\n")
	b.WriteString(fmt.Sprintf(`    "start": "tsx src/index.ts",`+"\n"))
	b.WriteString(fmt.Sprintf(`    "dev": "tsx watch src/index.ts",`+"\n"))
	b.WriteString(`    "build": "tsc",` + "\n")
	b.WriteString(`    "test": "vitest run",` + "\n")
	b.WriteString(`    "test:watch": "vitest"` + "\n")
	b.WriteString("  },\n")

	// Dependencies — sorted for deterministic output
	b.WriteString(`  "dependencies": {` + "\n")
	depKeys := sortedKeys(deps)
	for i, k := range depKeys {
		comma := ","
		if i == len(depKeys)-1 {
			comma = ""
		}
		b.WriteString(fmt.Sprintf(`    "%s": "%s"%s`+"\n", k, deps[k], comma))
	}
	b.WriteString("  },\n")

	// Dev dependencies — sorted for deterministic output
	b.WriteString(`  "devDependencies": {` + "\n")
	devKeys := sortedKeys(devDeps)
	for i, k := range devKeys {
		comma := ","
		if i == len(devKeys)-1 {
			comma = ""
		}
		b.WriteString(fmt.Sprintf(`    "%s": "%s"%s`+"\n", k, devDeps[k], comma))
	}
	b.WriteString("  }\n")
	b.WriteString("}\n")

	return codegen.OutputFile{Path: "package.json", Content: []byte(b.String())}
}

func (g *Generator) genTSConfig() codegen.OutputFile {
	content := `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "NodeNext",
    "moduleResolution": "nodenext",
    "esModuleInterop": true,
    "strict": true,
    "outDir": "dist",
    "rootDir": "src",
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "resolveJsonModule": true,
    "declaration": true,
    "declarationMap": true,
    "sourceMap": true
  },
  "include": ["src/**/*.ts"],
  "exclude": ["node_modules", "dist", "test"]
}
`
	return codegen.OutputFile{Path: "tsconfig.json", Content: []byte(content)}
}

func (g *Generator) genEnvExample(secrets []*ast.Secret, envs []*ast.Env) codegen.OutputFile {
	var b strings.Builder
	b.WriteString("# Generated by Blueprint — fill in your values\n\n")
	for _, s := range secrets {
		b.WriteString(fmt.Sprintf("%s=\n", s.Name))
	}
	if len(secrets) > 0 && len(envs) > 0 {
		b.WriteString("\n")
	}
	for _, e := range envs {
		val := exprToString(e.Value)
		b.WriteString(fmt.Sprintf("%s=%s\n", e.Name, val))
	}
	return codegen.OutputFile{Path: ".env.example", Content: []byte(b.String())}
}

func (g *Generator) genEnvTS(secrets []*ast.Secret, envs []*ast.Env, extraEnvVars ...string) codegen.OutputFile {
	var b strings.Builder
	b.WriteString(fileHeader(g.sourceFile))
	b.WriteString("import { z } from 'zod';\nimport 'dotenv/config';\n\n")
	b.WriteString("const envSchema = z.object({\n")

	// Track which env vars are already declared by secrets/envs to avoid duplicates
	declared := make(map[string]bool)
	for _, s := range secrets {
		declared[s.Name] = true
		req := ".optional()"
		if s.Required {
			req = ""
		}
		b.WriteString(fmt.Sprintf("  %s: z.string()%s,\n", s.Name, req))
	}

	// Add extra infra env vars (e.g., REDIS_URL for cache) that aren't already declared
	for _, name := range extraEnvVars {
		if !declared[name] {
			declared[name] = true
			b.WriteString(fmt.Sprintf("  %s: z.string(),\n", name))
		}
	}
	for _, e := range envs {
		zodType := "z.string()"
		defaultVal := exprToJS(e.Value)
		switch e.Value.(type) {
		case *ast.IntLit, *ast.FloatLit, *ast.SizeLit:
			zodType = "z.coerce.number()"
		case *ast.ListExpr:
			// List env vars: store as JSON string, parse on load
			zodType = "z.string().transform((v: string) => v.split(','))"
			// Convert list to comma-separated string default
			list := e.Value.(*ast.ListExpr)
			parts := make([]string, len(list.Elements))
			for i, el := range list.Elements {
				parts[i] = exprToString(el)
			}
			defaultVal = fmt.Sprintf(`"%s"`, strings.Join(parts, ","))
		case *ast.BinaryExpr:
			// Arithmetic expressions in env defaults are numeric
			zodType = "z.coerce.number()"
		case *ast.StringLit:
			// String default needs to be quoted
			defaultVal = fmt.Sprintf(`"%s"`, exprToString(e.Value))
		}
		b.WriteString(fmt.Sprintf("  %s: %s.default(%s),\n", e.Name, zodType, defaultVal))
	}
	b.WriteString("});\n\n")
	b.WriteString("export const env = envSchema.parse(process.env);\n")

	return codegen.OutputFile{Path: "src/lib/env.ts", Content: []byte(b.String())}
}

func (g *Generator) genErrors() codegen.OutputFile {
	var b strings.Builder
	b.WriteString(fileHeader(g.sourceFile))
	b.WriteString(`import type { ContentfulStatusCode } from 'hono/utils/http-status';

export class BpError extends Error {
  constructor(
    public statusCode: ContentfulStatusCode,
    message: string,
  ) {
    super(message);
    this.name = 'BpError';
  }
}

export class ValidationError extends BpError {
  constructor(message: string) {
    super(400, message);
    this.name = 'ValidationError';
  }
}

export class AuthError extends BpError {
  constructor(message: string) {
    super(401, message);
    this.name = 'AuthError';
  }
}

export class NotFoundError extends BpError {
  constructor(message: string) {
    super(404, message);
    this.name = 'NotFoundError';
  }
}
`)
	return codegen.OutputFile{Path: "src/lib/errors.ts", Content: []byte(b.String())}
}

func (g *Generator) genDB(bp *ast.Blueprint) codegen.OutputFile {
	var b strings.Builder
	b.WriteString(fileHeader(g.sourceFile))
	b.WriteString(`import { drizzle } from 'drizzle-orm/node-postgres';
import pg from 'pg';
import { env } from './env.js';
import * as schema from '../models/schema.js';

const pool = new pg.Pool({
  connectionString: env.DATABASE_URL,
});

export const db = drizzle(pool, { schema });
`)
	return codegen.OutputFile{Path: "src/lib/db.ts", Content: []byte(b.String())}
}

func (g *Generator) genStorage() codegen.OutputFile {
	var b strings.Builder
	b.WriteString(fileHeader(g.sourceFile))
	b.WriteString(`import { S3Client, PutObjectCommand, GetObjectCommand, DeleteObjectCommand } from '@aws-sdk/client-s3';
import { env } from './env.js';

const s3 = new S3Client({});

export async function upload(file: Buffer | ReadableStream, bucket: string, key?: string): Promise<{ url: string; key: string }> {
  const fileKey = key ?? crypto.randomUUID();
  await s3.send(new PutObjectCommand({ Bucket: bucket, Key: fileKey, Body: file as any }));
  return { url: ` + "`s3://${bucket}/${fileKey}`" + `, key: fileKey };
}

export async function download(bucket: string, key: string): Promise<ReadableStream> {
  const res = await s3.send(new GetObjectCommand({ Bucket: bucket, Key: key }));
  return res.Body as any;
}

export async function deleteObject(bucket: string, key: string): Promise<void> {
  await s3.send(new DeleteObjectCommand({ Bucket: bucket, Key: key }));
}
`)
	return codegen.OutputFile{Path: "src/lib/storage.ts", Content: []byte(b.String())}
}

func (g *Generator) genCache() codegen.OutputFile {
	var b strings.Builder
	b.WriteString(fileHeader(g.sourceFile))
	b.WriteString(`import { createClient } from 'redis';
import { env } from './env.js';

export const redis = createClient({ url: env.REDIS_URL });
redis.on('error', (err) => console.error('Redis error:', err));

export async function connectCache(): Promise<void> {
  if (!redis.isOpen) await redis.connect();
}

export async function cached<T>(key: string, ttlSeconds: number, fn: () => Promise<T>): Promise<T> {
  await connectCache();
  const hit = await redis.get(key);
  if (hit) return JSON.parse(hit) as T;
  const result = await fn();
  await redis.setEx(key, ttlSeconds, JSON.stringify(result));
  return result;
}
`)
	return codegen.OutputFile{Path: "src/lib/cache.ts", Content: []byte(b.String())}
}

// --- Dockerfile ---

func (g *Generator) genDockerfile() codegen.OutputFile {
	port := blueprintEntryInt(g.file.Blueprint, "port")
	if port == 0 {
		port = 3000
	}
	content := fmt.Sprintf(`FROM node:22-slim AS builder
WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm ci

COPY . .
RUN npx tsc

FROM node:22-slim
WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm ci --omit=dev

COPY --from=builder /app/dist ./dist

RUN addgroup --system app && adduser --system --ingroup app app
USER app

EXPOSE %d
CMD ["node", "dist/index.js"]
`, port)
	return codegen.OutputFile{Path: "Dockerfile", Content: []byte(content)}
}

// --- .gitignore ---

func (g *Generator) genGitignore() codegen.OutputFile {
	content := `node_modules/
dist/
.env
*.log
`
	return codegen.OutputFile{Path: ".gitignore", Content: []byte(content)}
}

// --- drizzle.config.ts ---

func (g *Generator) genDrizzleConfig() codegen.OutputFile {
	content := `import { defineConfig } from 'drizzle-kit';

export default defineConfig({
  schema: './src/models/schema.ts',
  out: './drizzle',
  dialect: 'postgresql',
  dbCredentials: {
    url: process.env.DATABASE_URL!,
  },
});
`
	return codegen.OutputFile{Path: "drizzle.config.ts", Content: []byte(content)}
}
