// Generated by Blueprint v0.2.0 from hello-world.bp
// Do not edit directly — modify the .bp source and run `bp build`
import { Hono } from 'hono';
import { BpError } from '../lib/errors.js';

export const healthRoutes = new Hono();

// GET /api/health
// Health check endpoint
healthRoutes.get('/api/health', async (c) => {
  try {
    return c.json({ status: "ok", version: "1.0.0" }, 200 as const);
  } catch (err) {
    if (err instanceof BpError) return c.json({ error: err.message }, err.statusCode);
    throw err;
  }
});

