// Generated by Blueprint from hello-world.bp
// Do not edit directly — modify the .bp source and run `bp build`
import { Hono } from 'hono';
import { BpError } from '../lib/errors.js';

export const helloRoutes = new Hono();

// GET /api/hello/:name
// Greeting endpoint
helloRoutes.get('/api/hello/:name', async (c) => {
  try {
    const name = c.req.param('name') || '';
    return c.json({ message: `Hello, ${name}!` }, 200 as const);
  } catch (err) {
    if (err instanceof BpError) return c.json({ error: err.message }, err.statusCode);
    throw err;
  }
});

