// Generated by Blueprint v0.3 from hello-world.bp
// Do not edit directly — modify the .bp source and run `bp build`
import { z } from 'zod';
import 'dotenv/config';

const envSchema = z.object({
});

export const env = envSchema.parse(process.env);
