// Generated by Blueprint v0.3 from hello-world.bp
// Do not edit directly — modify the .bp source and run `bp build`
export class BpError extends Error {
  constructor(
    public statusCode: number,
    message: string,
  ) {
    super(message);
    this.name = 'BpError';
  }
}

export class ValidationError extends BpError {
  constructor(message: string) {
    super(400, message);
    this.name = 'ValidationError';
  }
}

export class AuthError extends BpError {
  constructor(message: string) {
    super(401, message);
    this.name = 'AuthError';
  }
}

export class NotFoundError extends BpError {
  constructor(message: string) {
    super(404, message);
    this.name = 'NotFoundError';
  }
}
