// Generated by Blueprint from todo-api.bp
// Do not edit directly — modify the .bp source and run `bp build`
import { drizzle } from 'drizzle-orm/node-postgres';
import pg from 'pg';
import { env } from './env.js';
import * as schema from '../models/schema.js';

const pool = new pg.Pool({
  connectionString: env.DATABASE_URL,
});

export const db = drizzle(pool, { schema });
