// Generated by Blueprint v0.2.0 from todo-api.bp
// Do not edit directly — modify the .bp source and run `bp build`
import { z } from 'zod';
import 'dotenv/config';

const envSchema = z.object({
  DATABASE_URL: z.string(),
});

export const env = envSchema.parse(process.env);
